### ISSUE TITLE
Update IncrementPreviewVersion to support multiple major versions

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#102]
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/scripts/IncrementPreviewVersion.ps1#L54

It uses the preview version without regard to the major version. So, if 2.0.0-**preview.1** is published, the preview version of 1.22.0 is **preview.2** instead of **preview.1**

In the meantime, we can manually override the the versionSuffix in the csproj. 
[AB#7175](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7175)

**Comment by maisarissi** [comment]
Hi @MIchaelMainer . Am I wrong or has this been fixed already?
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/commit/c367d573f86f74a94c0d61559ef8a488b199aa45
