### ISSUE TITLE
Error: For Listing Users Parsing Select and Expand failed

### ISSUE THREAD

**Issue by chassq** [microsoftgraph/msgraph-sdk-dotnet-core#116]
The following Query is supported in beta but not in v1.0. It seems to have been this way for years now. Any idea on when this might get put into v.1.0? Or any idea of the plans for this? Best practices?

```
            var users = await client.Users.Request()
                            .Expand("appRoleAssignments")
                            .Top(100)
                            .GetAsync();
```

### Expected behavior
Work in both beta and v1.0

### Actual behavior
Works only in beta. Error returned from v1.0 is 
Code: BadRequest
    Message: Parsing Select and Expand failed.
    Inner error:
    	AdditionalData:
    	request-id: e91b775e-c75e-498a-88bb-a9d0b627c749
    	date: 2020-05-12T10:27:48

### Steps to reproduce the behavior
Return a list of users with Top() and use .Expand("appRoleAssignments").

**Comment by MIchaelMainer** [comment]
We don't have an ETA for when this will be supported at the v1.0 API endpoint, and hence, the v1.0 client library. 

change log: https://docs.microsoft.com/en-us/graph/changelog#identity-and-access-azure-ad-5
