### ISSUE TITLE
Microsoft.Graph.Core v2-preview2 causes exception in CalendarController.cs demo code

### ISSUE THREAD

**Issue by KarmaLlama** [microsoftgraph/msgraph-sdk-dotnet-core#119]
Since MGC v2.0.0-preview-2, the CalendarController code (..\msgraph-training-aspnetmvcapp\Demos\03-add-msgraph\graph-tutorial\Controllers\CalendarController.cs) returns an exception: -

System.NotSupportedException: The collection type 'Microsoft.Graph.IUserEventsCollectionPage' is abstract, an interface, or is read only, and could not be instantiated and populated.

The error is generated by line 58 of the CalendarController: -
var events = await graphClient.Me.Events.Request()** 

#Expected behavior
list of events

### Actual behavior
error above

### Steps to reproduce the behavior
Update NuGet package to Microsoft.Graph-Core v2.0.0-preview-2 or later.

### Workaround.
Rollback to Microsoft.Graph-Core v2.0.0-preview-1 or earlier. 
[AB#7177](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7177)

**Comment by MIchaelMainer** [comment]
This client is not yet ready to be used with the generated Microsoft.Graph library. Please revert to the 1.x.x of this library. We need to add a release note that it is intended to be used as a standalone library at this point.

**Comment by andrueastman** [comment]
I am closing this as the v2 preview packages are not to be used with the existing Service Library. That work is currently in progress and can be tracked via #80
