### ISSUE TITLE
Exception in LargeFileUploadTask ctor

### ISSUE THREAD

**Issue by DaleyKD** [microsoftgraph/msgraph-sdk-dotnet-core#120]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
https://microsoftgraph.github.io/msgraph-sdk-design/tasks/FileUploadTask.html

If you do a quick find on this page, you'll see that it mentions that the default slice size is 5 MB.  I see this number in multiple places, whether it's code or docs.

I'd expect that if I don't give the `LargeFileUploadTask` ctor a value for `maxSliceSize`, it would use 5 MiB.

### Actual behavior
The default is 4 MiB, which throws an exception, because it's not fully divisible by 320 KiB.

### Steps to reproduce the behavior
```csharp
var uploadSession = await _client.Drives[_driveID].Items[_driveItemID].ItemWithPath(fileName).CreateUploadSession().Request().PostAsync();
var largeFileUploadTask = new LargeFileUploadTask<DriveItem>(uploadSession, ms);
```

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/b2d9d7ce3073aabd8a65b7157f49ced0c9e28b27/src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs#L16-L19

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/b2d9d7ce3073aabd8a65b7157f49ced0c9e28b27/src/Microsoft.Graph.Core/Tasks/LargeFileUploadTask.cs#L47-L51

Since 5 MiB is divisible by 320 KiB, can we just change the constant in the class?

_Side Question_
Should we be using `LargeFileUploadTask` now or `ChunkedUploadProvider`? The link I gave above for docs suggests `LargeFileUploadTask`.

**Comment by MIchaelMainer** [comment]
Please use LargeFileUpload task.
