### ISSUE TITLE
Please Upgrade [Newtonsoft.Json] to the latest version

### ISSUE THREAD

**Issue by Kerryway** [microsoftgraph/msgraph-sdk-dotnet-core#125]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ ] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ ] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Please Upgrade [Newtonsoft.Json] to the latest version

### Steps to reproduce the behavior

 
[AB#7178](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7178)

**Comment by MIchaelMainer** [comment]
What reason is driving this request? The package allows you to use later versions.

**Comment by michael-hawker** [comment]
I don't know if this is related, but I'm hitting a 

```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonTextReader.ParseValue()
```

while trying to deserialize an Event from CalendarView.

However, I'd suggest at this point it's time to move to the `System.Text.Json` package instead of `Newtonsoft.Json`, eh?

**Comment by michael-hawker** [comment]
🦙 This should be closed as the work is already proceeding to move to `System.Text.Json` see #80.

**Comment by andrueastman** [comment]
I am closing this issue since we are moving over to System.Text.Json. Some work is already out in the latest release of the v2 preview packages for the Core Library.
Work is in progress in the Service Library and can be followed via #80
