### ISSUE TITLE
Remove NuGet feed reference to internal feed

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#127]
This blocks PR validation for PRs initiated by folks without access to the internal NuGet feed.

This is an example PR validation blocked by this https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/124

[AB#5592](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5592)

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/221/commits/63a247caa754b17af82f24a5117257386a9f573d
