### ISSUE TITLE
Add support for CancellationToken in LargeFIleUploadTask

### ISSUE THREAD

**Issue by mrjfalk** [microsoftgraph/msgraph-sdk-dotnet-core#132]
Currently many methods in the Graph SDK does allow passing on a CancellationToken, but unfortunately it doesn't seem to be possible for the LargeFileUploadTask methods. For obvious reasons it would be very beneficial if it was possible to cancel large file uploads using the SDK.
So my request is to add a CancellationToken parameter to the methods LargeFileUploadTask.UploadAsync(), LargeFileUploadTask.ResumeAsync(), and LargeFileUploadTask.DeleteAsync().
I tried to fast hack in a copy of the code myself, and seems to be relatively easy because UploadSliceRequest.PutAsync() method which is used internally already has a method accepting a CancellationToken.
Open question:

Currently UploadSliceRequest.PutAsync() wraps the OperationCancelledException in a ServiceException if it is cancelled. Not sure if this is desirable as a developer might expect (I did at least) to be able to catch a OperationCancelledException if passing a CancellationToken.
[AB#5874](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5874)

**Comment by mfeingol** [comment]
Now that ChunkedUploadProvider is deprecated and people will be switching to LargeFileUploadTask, this ask is even more relevant.

Please provide us with a way to cancel an upload request. I've tried calling DeleteSessionAsync on the task, but that doesn't result in cancellation.

Thanks.

**Comment by mfeingol** [comment]
@andrueastman - any thoughts on whether this might be taken up in the future? Thanks.

**Comment by 23W** [comment]
Yep, i was shocked that after switching from `CancellationToken` to `LargeFIleUploadTask` i lost the upload canceling feature.


Following example doesn't work. After upload canceling it should catch `OperationCanceledException` exception.
```
try
{
    var cts = new CancellationTokenSource();
    using (var fileStream = new FileStream(MyFilePath, FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize: 4096, useAsync: true))
    {
        var session = await client.Drives[DiskId].Items[ItemId].CreateUploadSession().Request().PostAsync(cts.Token);
        var uploader = new LargeFileUploadTask<DriveItem>(session, fileStream, uploadChunkSize, client);
        var uploaderTask = uploader.UploadAsync();
    
        await Task.Delay(100);   // wait some time period
        cts.Cancel();                   // cancel uploading
    
        await uploaderTask;
    }
}
catch (OperationCanceledException)
{
      // uploading has been canceled, newer works
}
catch (Exception e)
{
       // process error
}
```

**Comment by JosHuybrighs** [comment]
Until support for `CancellationToken `in `LargeFileUploadTask `has been taken care of, we have to use our own implementation for chunked upload. This is how it can look like:

```
public StorageDeviceErrorCode UploadFile(IStorageDevice srcDevice, string sourceFilePathName, string destinationFilePathName,
					 Action<CopyProgress> progressDelegate, CancellationToken cancellationToken, out string errMsg,
					 bool allowOverwrite, DateTime createdDateTime, DateTime modifiedDateTime)
{
	try
	{
		bool succeeded = false;
		using (Stream srcStream = srcDevice.OpenRead(sourceFilePathName))
		{
			if (srcStream != null)
			{
				var fileLength = srcStream.Length;
				DriveItemUploadableProperties props = new DriveItemUploadableProperties();
				props.FileSystemInfo = new Microsoft.Graph.FileSystemInfo()
				{
					CreatedDateTime = createdDateTime.ToUniversalTime(),
					LastModifiedDateTime = modifiedDateTime.ToUniversalTime()
				};
				var uploadSession = _graphClient.Me.Drive.Root.ItemWithPath(destinationFilePathName).CreateUploadSession(props).Request()
																															   .PostAsync()
																															   .GetAwaiter()
																															   .GetResult();

				int KiBUnits = (int)(srcStream.Length / (320 * 1024));
				if (KiBUnits == 0) KiBUnits = 1;
				if (KiBUnits > 180) KiBUnits = 180; // Limit maxChunkSize to ~60MB
				int maxChunkSize = KiBUnits * 320 * 1024;

				var uploadProvider = new ChunkedUploadProvider(uploadSession, _graphClient, srcStream, maxChunkSize);
				// These are the chunk requests that will be made
				var chunkRequests = uploadProvider.GetUploadChunkRequests();

				List<Exception> trackedExceptions = new List<Exception>();
				DriveItem uploadedFile = null;

				// Upload the chunks
				foreach (var request in chunkRequests)
				{
					// Send chunk request
					UploadChunkResult result = uploadProvider.GetChunkRequestResponseAsync(request, trackedExceptions)
															 .GetAwaiter()
															 .GetResult();
					if (cancellationToken.IsCancellationRequested)
					{
						uploadProvider.DeleteSession();
						break;
					}
					if (progressDelegate != null)
					{
						progressDelegate(new CopyProgress() { BytesCopied = request.RangeEnd, TotalLength = fileLength });
					}

					if (result.UploadSucceeded)
					{
						succeeded = true;
						uploadedFile = result.ItemResponse;
						// Contains file data
					}
				}
				if (uploadedFile == null &&
					!cancellationToken.IsCancellationRequested)
				{
					// Retry upload ??
				}
				errMsg = "";
			}
			else
			{
				errMsg = srcDevice.LastError;
			}
		}
		return cancellationToken.IsCancellationRequested
			? StorageDeviceErrorCode.Canceled
			: succeeded ? StorageDeviceErrorCode.None : StorageDeviceErrorCode.CopyFailed;
	}
	catch (Microsoft.Graph.ServiceException e1)
	{
		errMsg = e1.Error.Message;
		return ExceptionToErrorCode(e1);
	}
	catch (Exception e2)
	{
		errMsg = e2.Message;
		return StorageDeviceErrorCode.UnhandledException;
	}
}

```
The example uses a synchroneous `UploadFile `method and therefore the use of `GetAwaiter().GetResult()`. You are of course free to make an async version (and remove the `GetAwaiter().GetResult()` calls).

The problem with this approach is of course that cancellation will take place after a chunk has been uploaded. If the chunk is big and your upstream connection is not so fast it will take some time before the cancellation kicks in. One could then make the max chunk size smaller but that will have a negative effect on the overall upload speed.

@andrueastman  We need `CancellationToken `in `LargeFileUploadTask `and if possible also at the HTTP layer.

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/457

**Comment by mfeingol** [comment]
That's exciting. @andrueastman any idea which version this will go out in?
