### ISSUE TITLE
Wrong ordering on add images to OneNote page from pdf content

### ISSUE THREAD

**Issue by eiriksanderfjeld** [microsoftgraph/msgraph-sdk-dotnet-core#133]
When i add a PDF to a OneNote page as a multipart request it seems like the ordering of the pages are sorted alphabetically instead of lexical order. The pages in the PDF are numbered (1-22) but when the page has been updated with the content from the PDF, the order of the images are 1, 10, 11, 12..2, 20, 21, 22)

How can i prevent or control this behaviour?

I am updating this page as recommended in the documentation: [https://docs.microsoft.com/en-us/graph/onenote-images-files#add-images-of-pdf-file-contents](https://docs.microsoft.com/en-us/graph/onenote-images-files#add-images-of-pdf-file-contents). 
 
[AB#7179](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7179)

**Comment by MIchaelMainer** [comment]
Can you post this to StackOverflow and tag it microsoft-graph and onenote? We should get more eyes on this scenario that way. Please provide a link to the post in this issue.

**Comment by eiriksanderfjeld** [comment]
I've created a post on stackoverflow 3 weeks ago, no comments. I had tagged it with microsoft-graph-onenote, added the onenote tag as well. 

https://stackoverflow.com/questions/63337830/wrong-ordering-on-add-images-of-pdf-file-content

**Comment by maisarissi** [comment]
Hi @eiriksanderfjeld 

As this is not an SDK issue, there isn't much that we can do.
I have posted this in the Microsoft Q&A. You can follow up from here: https://docs.microsoft.com/en-us/answers/questions/972575/wrong-ordering-on-add-images-to-onenote-page-from.html

Closing the issue.
