### ISSUE TITLE
Attempting to deserialize a String type

### ISSUE THREAD

**Issue by mlafleur** [microsoftgraph/msgraph-sdk-dotnet-core#134]
When executing the code below, the following exception is thrown:

Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path '', line 1, position 1.'

Example Code:
await client
    .Education
    .SynchronizationProfiles[syncProfileId]                    
    .UploadUrl()
    .Request()
    .GetAsync()
From a cursory review, it looks like the issue occurs in ResponseHandler.HandleResponse<T>. Putting aside the actual exception, it seems unnecessary to even attempt to deserialize a String type into a String type.
[AB#6102](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6102)

**Comment by MIchaelMainer** [comment]
@mlafleur Sounds like the documentation sample response is incorrect. The documentation demonstrates a json object. 

https://docs.microsoft.com/en-us/graph/api/educationsynchronizationprofile-uploadurl?view=graph-rest-beta&tabs=http#response-1

```http
HTTP/1.1 201 OK
Content-type: application/json
Content-length: 314

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#String",
    "value": "https://sdsstorage.blob.core.windows.net/86904b1e-c7d0-4ead-b13a-98f11fc400ee?sv=2015-07-08&sr=c&si=SharedAccessPolicy_20170704044441&sig=CH65vxxqXETCkQNH0Lfsu31cUo0s0XcEEo0OE2YiL6Q%3D&se=2017-07-04T08%3A43%3A01Z&sp=w"
}
```

I don't have a tenant with this license. Is the content-type `text/plain`? If so then we can use that to short-circuit the current deserialization and just return the content.

**Comment by MIchaelMainer** [comment]
We have 11 functions and 10 actions that return string. What I can't find yet is where in OData spec does it say that methods that return primitives should return the primitives as plain text.

**Comment by mlafleur** [comment]
I double-checked and the content-type is `application/json` so the documentation is correct.  

My suspicion was that either `JsonSerializer.Deserialize<string>` or `JsonReader` is failing to recognize `value` is a string.
