### ISSUE TITLE
How to get correlation ID from a ServiceException?

### ISSUE THREAD

**Issue by joshfriend** [microsoftgraph/msgraph-sdk-dotnet-core#138]
`MsalServiceException` from MSAL.NET has a `CorrelationId` property that identifies the client request that caused the exception, but `ServiceException` seems to have no equivalent. Is there a way to obtain it? 
[AB#6267](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6267)

**Comment by andrueastman** [comment]
@ddyett 
The [GraphResponse](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/6ae4d2ced4e9dc362170cb084f49498fc430ba89/src/Microsoft.Graph.Core/Requests/GraphResponse.cs#L42) object does expose the http headers of the response from graph.
I believe you should be able to get the headers from this.
