### ISSUE TITLE
Places Api doesn't work

### ISSUE THREAD

**Issue by Kuchen2020** [microsoftgraph/msgraph-sdk-dotnet-core#141]
### Expected behavior
Hi everyone, 
I' am trying to filter displayName from ms graph api.

The following request in ms graph for place works fine!

https://graph.microsoft.com/v1.0/places/microsoft.graph.room

All necessary permissions are consented: 

Place.Read.All    Read all company places    Consented

### Actual behavior
Request place from api and filter displayName by this code:

```
public async Task<string> GetRoomName(string roomId)
        {
            var graphClient = await GetClient();

            string resultname = "";

            var room = await graphClient.Places
                .Request()
                .GetAsync();

            resultname = room.Where(item => item.DisplayName == "xxx").FirstOrDefault().DisplayName;

            return resultname;
        }
```

### Failure Response:

**An unhandled exception has occurred while executing the request.
Status Code: NotAcceptable
Microsoft.Graph.ServiceException: Code: UnknownError**

### Steps to reproduce the behavior
IDE VS Code
ms graph version 3.15.0
C#  .NET Core 3.1 ASP.NET

 
[AB#7182](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7182)

**Comment by MIchaelMainer** [comment]
Thank you for brining this to our attention. This is an issue in our client. The call `await graphClient.Places.Request().GetAsync();` is only calling `https://graph.microsoft.com/v1.0/places`. We need to support the filter on rooms.

**Notes for self**
This will require the cast derived type constraint annotation:
- [ ] add new https://github.com/microsoftgraph/msgraph-metadata/pull/33/files
- [ ] add support in generator for .NET like what has been done in Java.

**Comment by MIchaelMainer** [comment]
@Kuchen2020 here's a workaround or now:

```csharp
var url = graphClient.Places.RequestUrl + "microsoft.graph.room";
var rb = new GraphServicePlacesCollectionRequestBuilder(url, graphClient);
var page = await rb.Request().GetAsync();
```

**Comment by andrueastman** [comment]
We will need to investigate why the xslt rule at the link below isn't adding the annotation to the metadata.

https://github.com/microsoftgraph/msgraph-metadata/blob/2bffb30b12b597ed59abd6475c2fd504c553925a/transforms/csdl/preprocess_csdl.xsl#L286

Fixing this should unblock this and enable us to close this issue as the conversion process should add the path and expose it in the SDK similar to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/836

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-metadata/pull/160. 

Changes should be available in the latest Koita preview packages of the SDK.
