### ISSUE TITLE
PageIterator StackoverflowException on large dataset

### ISSUE THREAD

**Issue by runningdavid** [microsoftgraph/msgraph-sdk-dotnet-core#16]
Please provide the following (and please check them off the list with [x]) before submitting this issue:

### Expected behavior
PageIterator should run problem free on large dataset (large # of pages). I'm using the Microsoft corporate data from Graph.

### Actual behavior
PageIterator causes Stackoverflow exception after running 45 mins.

### Steps to reproduce the behavior
Perform an initial delta sync on all users in the Microsoft corporation (tenant), using the latest PageIterator from the Core library.

Reading into the source code it could be caused by a mutual recursion between InterpageIterateAsync() and IterateAsync() which throws stackoverflow exception when operate on a large number of pages. Changing the code to use a loop should resolve this issue.

**Comment by darrelmiller** [comment]
Thanks for the bug report and detailed explanation.  We will investigate and fix as required.

**Comment by MIchaelMainer** [comment]
Thank you for reporting this. Yes, this is unbounded recursion. 

Since we can't know the number of pages:
* Add nextlink loop detection in case service API returns looped nextLinks.
* Add a control loop that when exhausted, ends the recursion, stores state, and then restarts the iterator.

**Comment by runningdavid** [comment]
Thanks for the response. I think it might be better to replace the recursive functions with a loop altogether but I'm not sure how much rewrite that would cause. The idea to detect looped nextLink is great!

**Comment by MIchaelMainer** [comment]
You're correct. It would be much better to replace the recursive functions with a loop. Thank you for guidance and persistence!

**Comment by runningdavid** [comment]
We are implementing our data pipeline with the Graph SDK now and I'm currently using a loop I wrote myself to replace the PageIterator. Would you mind providing an ETA for the fix so I can continue use the PageIterator from the SDK?

**Comment by MIchaelMainer** [comment]
@runningdavid I'm looking at mid August now as I'm out of office for a couple of weeks. 

My current thoughts on this:
* Fix the bad recursion with a loop and detect nextlink loop. (August)
* Move PageIterator from Microsoft.Graph.Core to Microsoft.Graph - this PageIterator is intended to be used with the generated *Page models and the *Request and *RequestBuilder classes that are used to process NextLinks. The tests are in Microsoft.Graph. We will need to integrate into Microsoft.Graph.Beta.

Long term, I'd like to:
* Create a PageIterator<T> that takes an HttpResponseMessage and HttpClient (ideally from the GraphClientFactory), along with the delegate, to handle paging without using the *Request and *RequestBuilder classes.
