### ISSUE TITLE
Add Continuous Access Evaluation (CAE) support to AuthProviders

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-sdk-dotnet-core#166]
As requested, I have attached the links to the Reference Client and Documentation on how to onboard to CAE using MSAL.net.

 

Repo: https://msazure.visualstudio.com/One/_git/AAD-CCS-TestClient?version=GBAgsTestClient

Branch: AgsTestClient [This branch is specifically configured to call MS Graph on a test endpoint]

 

Docs: ​docx icon CAE Integration using MSAL.docx

Contact: Joel Mascarenhas

[AB#6390](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6390)

**Comment by andrueastman** [comment]
Implementation of this involves
- [x] Extracting www authenticate headers from forbidden response and put into GraphContext to enable retries to use claims information
- [x] Calling the relevant AuthProvider with the `WithClaims()` function with the info from GraphContext
