### ISSUE TITLE
HttpProviders throws NullReferenceException if response has no ContentType header

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/msgraph-sdk-dotnet-core#167]
### Expected behavior

A request that returns a non-2** status code results in a ServiceException.

### Actual behavior

A NullReferenceException is thrown.

### Steps to reproduce the behavior

Under certain conditions, the response does not contain a ContentType header. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/1f528e15953fae6da9fb3f971e45bbfdb313d94f/src/Microsoft.Graph.Core/Requests/HttpProvider.cs#L216

Example response:
```
HTTP/1.1 401 Unauthorized
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
WWW-Authenticate: Bearer realm="[redacted]"
x-ms-diagnostics: 3000006;reason="Token contains invalid signature.";category="invalid_client"
SPRequestGuid: 742c889f-f060-2000-62b5-88dc9dfd5f65
request-id: 742c889f-f060-2000-62b5-88dc9dfd5f65
MS-CV: n4gsdGDwACBitYjcnf1fZQ.0
X-Frame-Options: SAMEORIGIN
SPRequestDuration: 13
SPIisLatency: 2
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.20614
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: 15F6F9A58D934518820F1F9720E405B0 Ref B: CH1EDGE1015 Ref C: 2020-10-28T19:06:10Z
Content-Length: 52

{"error_description":"Invalid issuer or signature."}
```

**Comment by MIchaelMainer** [comment]
Microsoft Graph should be returning a ServiceException with contenttype set.
Client library should handle this scenario with grace.

@ificator Can you take a look at why SharePoint isn't returning an OData error response?
