### ISSUE TITLE
Create PageIterator for HttpRequestMessage with @odata.nextlink

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#17]
Related to #15 

Create a PageIterator that takes an HttpRequestMessage and HttpClient (ideally from the GraphClientFactory), along with the delegate, to handle paging without using the *Request and *RequestBuilder classes.

     new PageIterator(HttpRequestMessage, HttpClient, Func< bool>) 
[AB#7192](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7192)

**Comment by MIchaelMainer** [comment]
When using the service library, we know the type expected in the collection of items returned in the response. This allows the developer to pass a delegate to process each of the items (intrapage iteration). We can enqueue/dequeue each item in the page and make it available to the delegate. 

Without the service library, we can't know what the HttpResponseMessage.Content holds. This means the developer has to setup intrapage iteration in their delegate - we aren't providing this value (like we did for the service library). So, this leaves us with interpage iteration. We could iterate and queue HttpResponseMessage objects so that the customer defined intrapage iteration in their delegate can handle each HttpResponseMessage. We can make iteration resumeable in case of deltalink or if delegate stopped processing the content of an HttpResponseMessage (returned false).

**Comment by ddyett** [comment]
closing this as it's older and don't think we've seen requests for this recently.
