### ISSUE TITLE
UserJoinedTeamsCollectionWithReferencesRequest fails with ServiceException (UnknownError)

### ISSUE THREAD

**Issue by fuocor** [microsoftgraph/msgraph-sdk-dotnet-core#177]
UserJoinedTeamsCollectionWithReferencesRequest fails with ServiceException with the simple call:
```csharp
                var allTeams = await graphClient
                        .Me
                        .JoinedTeams
                        .Request()
                        .GetAsync();
```

The public client application is configured with the following scopes and the `Me` is `Global Administrator`
```
https://graph.microsoft.com/Directory.AccessAsUser.All
https://graph.microsoft.com/email
https://graph.microsoft.com/Group.ReadWrite.All
https://graph.microsoft.com/offline_access
https://graph.microsoft.com/openid
https://graph.microsoft.com/profile
https://graph.microsoft.com/User.Read
```

### Expected behavior

Something meaningful as a response

### Actual behavior

```
Message: 
    Microsoft.Graph.ServiceException : Code: UnknownError
    Inner error:
    	AdditionalData:
    	date: 2020-11-25T14:21:35
    	request-id: b4594c27-f5f5-4728-b67a-7fbf2049ca3e
    	client-request-id: b4594c27-f5f5-4728-b67a-7fbf2049ca3e
    ClientRequestId: b4594c27-f5f5-4728-b67a-7fbf2049ca3e
```

### Steps to reproduce the behavior

Version: `0.33.0-preview`
see code above

 
[AB#7187](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7187)

**Comment by ddyett** [comment]
try adding a scope for team.readbasic.all.

**Comment by fuocor** [comment]
Adding the scope to the application worked thanks.

The question I have is why do I need to explicitly add the scope to the application  permissions when I already have Directory.AccessAsUser.All defined?

Regards
Rich

**Comment by andrueastman** [comment]
Hey @fuocor,
Its great to hear that the suggestion worked out.
If you check out the documentation for the permissions of the api [here](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http#permissions), I believe you will see that the `Directory.AccessAsUser.All` scope is not listed in order to successfully access the api. 
To call any api, you would at least need a permission listed in its specification.
