### ISSUE TITLE
Constructing a Microsoft.Graph.List object raises InvalidCastException

### ISSUE THREAD

**Issue by famastefano** [microsoftgraph/msgraph-sdk-dotnet-core#191]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

Doc Issue already opened: [microsoft-graph-docs/issues/11146](https://github.com/microsoftgraph/microsoft-graph-docs/issues/11146).

### Expected behavior

List object successfully created as stated here: [Create a new list](https://docs.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&tabs=csharp).

### Actual behavior

List creation raises InvalidCastException when casting the `List<ColumnDefinition>` to `IListColumnsCollectionPage`.

### Steps to reproduce the behavior

Microsoft.Graph: 3.21.0
VS 2019 Enterprise 16.8.3

1. Copy/Paste the code in the docs example
2. Run

```csharp
var list = new List
{
    Name = "ListName",
    ListInfo = new ListInfo { Template = "genericList" },
    Columns = (IListColumnsCollectionPage)new List<ColumnDefinition>
    { }
};
``` 
[AB#7189](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7189)

**Comment by andrueastman** [comment]
@famastefano The code example was incorrect and has been updated appropriately as follows.

```cs
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var list = new List
{
	DisplayName = "Books",
	Columns = new ListColumnsCollectionPage()
	{
		new ColumnDefinition
		{
			Name = "Author",
			Text = new TextColumn
			{
			}
		},
		new ColumnDefinition
		{
			Name = "PageCount",
			Number = new NumberColumn
			{
			}
		}
	},
	ListInfo = new ListInfo
	{
		Template = "genericList"
	}
};

await graphClient.Sites["{site-id}"].Lists
	.Request()
	.AddAsync(list);
```

Closing this for now as the docs have been updated.
