### ISSUE TITLE
Inject .NET Core's HttpClient via IHttpClientFactory vs. using GraphClientFactory?

### ISSUE THREAD

**Issue by felinepc** [microsoftgraph/msgraph-sdk-dotnet-core#202]
I'm using the ```Microsoft.Graph``` SDK in my ASP.NET Core project, and want to take advantage of .NET Core's ```HttpClient``` management via ```IHttpClientFactory```.

I see that ```GraphServiceClient``` accepts a ```HttpClient``` parameter in its constructor, allowing me to inject a  ```HttpClient``` directly. It seems to be working fine.

But I did notice the constructor's documentation says:

> The System.Net.Http.HttpClient to use for making requests to Microsoft Graph. Use the ```Microsoft.Graph.GraphClientFactory``` to get a pre-configured HttpClient that is optimized for use with the Microsoft Graph service API

The typed ```HttpClient``` instance I'm injecting in is the default one created by .NET Core's ```IHttpClientFactory```. Does it need some extra configuration to be "optimized" for use with the Graph SDK?

So is it better to use it like this, or use ```Microsoft.Graph.GraphClientFactory```?

Your clarification would be appreciated.

 
[AB#8053](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8053)

**Comment by andrueastman** [comment]
@felinepc 

If you checkout the code [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/19469736e35445b3a6b34fe1008821c83db597e8/src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs#L122), you will see the handlers that are added to the HttpClient if you use `Microsoft.Graph.GraphClientFactory`.

If you use the default `HttpClient` you will have a client that is not tailored/configured with optimal ways to handle Compression, Redirects, Retries and also Authentication on the Graph Service.

**Comment by felinepc** [comment]
@andrueastman Thanks for pointing me to the source code. Upon analyzing what `GraphClientFactory` does, I did the following to emulate its behavior using ASP.NET Core's DI and `HttpClientFactory` (using typed client):

```
//Register Graph's HttpMessageHandler via DI
services.AddTransient<CompressionHandler>();
services.AddTransient<RetryHandler>();
services.AddTransient<RedirectHandler>();

//Register a similarly-configured, typed HttpClient to inject into my service code
//which then is passed in to construct GraphServiceClient
services.AddHttpClient<IMicrosoftGraphService, MicrosoftGraphService>(client =>
{
    client.DefaultRequestHeaders.CacheControl = new CacheControlHeaderValue { NoCache = true, NoStore = true };
})
   .AddHttpMessageHandler<CompressionHandler>()
   .AddHttpMessageHandler<RetryHandler>()
   .AddHttpMessageHandler<RedirectHandler>();
```
I did not need a `AuthenticationHandler` here because I provide my own at runtime.

Compared to the source code, I did not add the `DefaultRequestHeaders` that sets the SDK client versions, and I did not `SetFeatureFlag`. I assume these are not vitally important?

Do you think my implemenenations here seems okay?

**Comment by andrueastman** [comment]
> Compared to the source code, I did not add the DefaultRequestHeaders that sets the SDK client versions, and I did not SetFeatureFlag. I assume these are not vitally important?
That is true.

**Comment by andrueastman** [comment]
Otherwise, this looks good really. 
If its all works out for you, please feel free to close the issue and open a new one in the event you run into any issues.
