### ISSUE TITLE
Remove code to serialize headers and content into AdditionalData

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-dotnet-core#206]
Now we have the ServiceLibrary that returns GraphResponse we no longer need to expose this information via AdditionalData.  Removing this should have a significant impact on memory footprint. 
[AB#8217](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8217)

**Comment by andrueastman** [comment]
Closed via #208
