### ISSUE TITLE
Bump Version issues when try update Microsoft.Graph.Core from 1.23 to 1.24

### ISSUE THREAD

**Issue by yiwenwang-ms** [microsoftgraph/msgraph-sdk-dotnet-core#210]
Hi team,

I met an issue when I am trying to update Microsoft.Graph.Core from 1.23 to 1.24 due to the change of **BaseFunctionMethodRequestBuilder.cs.**

I'd like to know if it is a break change or bug.
Please compare the Request method in BaseFunctionMethodRequestBuilder.cs.

If we implement CreateRequest, when user trigger Request, it will trigger CreateRequest we overrided.

1.23 will pass an url with options
1.24 just pass a base url.

so that we need to change our whole project implementation of the createRequest.

[AB#8258](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8258)

**Comment by maisarissi** [comment]
Hi @yiwenwang-ms .

Sorry for the late late response.
Is this issue still valid? Are you using core directly on your application or are you using the service library?

I also just want to make sure you know that we are at core version 2 now.
