### ISSUE TITLE
Align large file upload on new spec

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet-core#215]
see changes in https://github.com/microsoftgraph/msgraph-sdk-design/pull/42 (naming convention, return type, behavior...) 
[AB#8286](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8286)

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/457
