### ISSUE TITLE
Add ability to build the project with dotnet CLI

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-dotnet-core#227]
Currently the project can only be built by msbuild. `dotnet build` hits the following error:
```
C:\github\msgraph-sdk-dotnet-core\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj :
  error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.
```

This might be relevant: https://github.com/novotnyllc/MSBuildSdkExtras/issues/85 
[AB#8736](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8736)

**Comment by maisarissi** [comment]
Hi @zengin . This bug is due to .Net SDK TFMs limitations:  https://github.com/dotnet/sdk/issues/491

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/486
