### ISSUE TITLE
Developers get access to all actionable information in exception classes

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-dotnet-core#23]
This is a high level summary issue to keep track of work that needs to be done on the Exception classes in the core library.

- [x] In some scenarios some error response information is lost. https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/316
- [x] ClientRequestId should be exposed as a first class property on the Error object.
- [x] Support full [error response body](http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part1-protocol/odata-v4.01-csprd05-part1-protocol.html#_Toc14172757).

**Comment by pschaeflein** [comment]
Calls to DirectoryObject.ValidateProperties provide valuable information in the response, even when the response has a non-2xx status code.

```
POST /v1.0/directoryObjects/microsoft.graph.validateProperties 

{"entityType":"Group","displayName":"Dark mode","onBehalfOfUserId":"64a7ee41-snipped"}

HTTP/1.1 422 Unprocessable Entity

{
  "error": {
        "code": "Request_UnprocessableEntity",
        "message": "The values provided contain one or more validation errors.",
        "innerError": {
            "request-id": "cc6d775d-55dd-44f8-87d2-992094b0407f",
            "date": "2019-08-30T16:58:56"
        },
        "details": [
            {
                "target": "displayName",
                "code": "ContainsBlockedWord",
                "message": "The displayName cannot contain the blocked word 'dark' as per company policy.",
                "blockedWord": "dark"
            }
        ]
    }
}
```

**Comment by MIchaelMainer** [comment]
We need to implement the full [error response body](http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part1-protocol/odata-v4.01-csprd05-part1-protocol.html#_Toc14172757) spec to address the issue brought up by @pschaeflein. @pschaeflein I think you can still get the details from the AdditionalData bag.

**Comment by pschaeflein** [comment]
Confirmed: details are accessible via serviceException.Error.AdditionalData:

![image](https://user-images.githubusercontent.com/8008013/64386726-7bac2480-cfff-11e9-9ee0-16c92dcf3dba.png)

Thanks.
