### ISSUE TITLE
Return error content

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-dotnet-core#24]
[spec](https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/content/ErrorContent.md).
Also, all client related exceptions should be thrown as ClientExceptions. 
[AB#7194](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7194)

**Comment by ddyett** [comment]
@andrueastman was this the same as the GraphResponse work?

**Comment by andrueastman** [comment]
Closing this as this is resolved through the GraphResponse
