### ISSUE TITLE
URL encode request URLs

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#248]
There are times when data from graph response is used in request URLs as query parameters. The data strings may need to be encoded before being sent.

https://stackoverflow.microsoft.com/questions/252716 
[AB#9234](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9234)

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/914

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/700

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/881

**Comment by andrueastman** [comment]
This is now closed via #255 and available through https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.0-preview.12
