### ISSUE TITLE
Make a sample or available connector using the Graph API in it's entirety available out of the box for Power BI

### ISSUE THREAD

**Issue by cvillegashak** [microsoftgraph/msgraph-sdk-dotnet-core#250]
Add tutorial for creation of creating a Power BI connector with the Microsoft Graph since the legacy beta connector no longer exists. I don't know where to add this at this point since the former OpenAPI specifications all appear to have been removed or archived.

 
[AB#9304](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9304)

**Comment by andrueastman** [comment]
Hey @cvillegashak,

Are you able to provide more information on the legacy connector and where it resided?
