### ISSUE TITLE
GraphClientFactory does not appear to support US Government L5 (DOD) national cloud endpoint

### ISSUE THREAD

**Issue by tjmoore** [microsoftgraph/msgraph-sdk-dotnet-core#253]
The cloud list in `GraphClientFactory` for mapping national cloud to endpoints does not include the US Gov L5 (DOD) endpoint.

e.g.

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
```csharp
private static readonly Dictionary<string, string> cloudList = new Dictionary<string, string>
	{
		{ Global_Cloud, "https://graph.microsoft.com" },
		{ USGOV_Cloud, "https://graph.microsoft.us" },
		{ China_Cloud, "https://microsoftgraph.chinacloudapi.cn" },
		{ Germany_Cloud, "https://graph.microsoft.de" }
	};
```

According to https://docs.microsoft.com/en-us/graph/deployments there should be an endpoint for

https://dod-graph.microsoft.us

 
[AB#9512](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9512)

**Comment by andrueastman** [comment]
This is now closed via #259 and should be available through  https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.0-preview.13
