### ISSUE TITLE
Create response object to wrap entire response

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#26]
microsoftgraph/msgraph-sdk-dotnet#361
[AB#6147](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6147)

**Comment by darrelmiller** [comment]
Add something like this to BaseRequest

```csharp
        public async Task<GraphResponse> SendAsyncWithGraphResponse() {
            using (var response = await this.SendRequestAsync(serializableObject, cancellationToken, completionOption).ConfigureAwait(false))
            {
                return new GraphResponse(response);
            }
        }
```

**Comment by andrueastman** [comment]
https://github.com/microsoftgraph/msgraph-sdk-design/blob/mm/dotnetResponse/content/ResponseObject.md

**Comment by MIchaelMainer** [comment]
@ddyett Why close this? I think this is important for our long term plans.

**Comment by ddyett** [comment]
this reads like the graph response work which is checked in against in. If it's meant to represent something else then probably should open a new clean issue that represents that.
