### ISSUE TITLE
GraphClientFactory does not appear to support china ational cloud endpoint 

### ISSUE THREAD

**Issue by KallerLong1** [microsoftgraph/msgraph-sdk-dotnet-core#261]
below  is my code:
`// Initialize the client credential auth provider
            IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(config.AppId)
                .WithTenantId(config.TenantId)
                .WithClientSecret(config.ClientSecret)
                .WithAuthority(new Uri(config.Authority))
                .Build();

            ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);

            // Set up the Microsoft Graph service client with client credentials
            var httpClient = GraphClientFactory.Create(authProvider, nationalCloud: GraphClientFactory.China_Cloud);
            GraphServiceClient graphClient = new GraphServiceClient(httpClient);
            graphClient.BaseUrl = "https://microsoftgraph.chinacloudapi.cn/v1.0";`

Error Message:
An error occurred: Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> Microsoft.Graph.Auth.AuthenticationException: Code: generalException
Message: Unexpected exception returned from MSAL.

 ---> MSAL.NetCore.4.32.0.0.MsalServiceException:
        ErrorCode: invalid_resource
Microsoft.Identity.Client.MsalServiceException: AADSTS500011: The resource principal named https://graph.microsoft.com was not found in the tenant named 41ebb163-adc1-4068-9087-eb79c718b633. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
 
[AB#9846](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9846)

**Comment by andrueastman** [comment]
Hey @KallerLong1, Thanks for raising this issue.

In 
```cs
IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
.Create(config.AppId)
.WithTenantId(config.TenantId)
.WithClientSecret(config.ClientSecret)
.WithAuthority(new Uri(config.Authority))
.Build();
```

What value do you provide for `config.Authority`? I suspect that may be the cause of the issue. The values should ideally be one of the values provided [here](https://docs.microsoft.com/en-us/graph/deployments#app-registration-and-token-service-root-endpoints).

**Comment by KallerLong1** [comment]
@andrueastman  
The config.Authority value is https://login.partner.microsoftonline.cn/41ebb163-adc1-4068-9087-eb79c718b633

**Comment by KallerLong1** [comment]
> Hey @KallerLong1, Thanks for raising this issue.
> 
> In
> 
> ```cs
> IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
> .Create(config.AppId)
> .WithTenantId(config.TenantId)
> .WithClientSecret(config.ClientSecret)
> .WithAuthority(new Uri(config.Authority))
> .Build();
> ```
> 
> What value do you provide for `config.Authority`? I suspect that may be the cause of the issue. The values should ideally be one of the values provided [here](https://docs.microsoft.com/en-us/graph/deployments#app-registration-and-token-service-root-endpoints).

**Comment by LuBu0505** [comment]
For Mooncake( China Azure). use below code to get user info:


```
        String clientId = "";
        String clientSecret = "";
        String tenantId = "";

        // The client credentials flow requires that you request the
        // /.default scope, and pre-configure your permissions on the
        // app registration in Azure. An administrator must grant consent
        // to those permissions beforehand.
        java.util.List<String> scopes = Arrays.asList("https://microsoftgraph.chinacloudapi.cn/.default");
        ClientSecretCredential credential = new ClientSecretCredentialBuilder()
                .authorityHost("https://login.partner.microsoftonline.cn/")
                .clientId(clientId).tenantId(tenantId).clientSecret(clientSecret).build();
        if (null == scopes || null == credential) {
            throw new Exception("Unexpected error");
        }
        TokenCredentialAuthProvider authProvider = new TokenCredentialAuthProvider(
                scopes, credential);
        GraphServiceClient<okhttp3.Request> graphClient = GraphServiceClient.builder()
                .authenticationProvider(authProvider).buildClient();

        // Specify the user principal name
        String userPrincipalName = "your user principal name";

        graphClient.setServiceRoot("https://microsoftgraph.chinacloudapi.cn/v1.0");

        // Use the GraphServiceClient to get the user by user principal name
        User user = graphClient.users(userPrincipalName)
                .buildRequest()
                .get();

        // Get the user object ID
        String objectId = user.id;

```
