### ISSUE TITLE
GraphClientFactory does not appear to support china ational cloud endpoint

### ISSUE THREAD

**Issue by KallerLong1** [microsoftgraph/msgraph-sdk-dotnet-core#264]
the code is below
`
// Initialize the client credential auth provider
            IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(config.AppId)
                .WithTenantId(config.TenantId)
                .WithClientSecret(config.ClientSecret)
                .WithAuthority(AzureCloudInstance.AzureChina, config.TenantId, true)
                .Build();

            //AuthorizationCodeProvider authProvider = new AuthorizationCodeProvider(confidentialClientApplication);
            ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);

            // Set up the Microsoft Graph service client with client credentials
            var httpClient = GraphClientFactory.Create(authProvider, nationalCloud: GraphClientFactory.China_Cloud);
            GraphServiceClient graphClient = new GraphServiceClient(httpClient);
            graphClient.BaseUrl = "https://microsoftgraph.chinacloudapi.cn/v1.0";
`

Error Message:
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> Microsoft.Graph.Auth.AuthenticationException: Code: generalException
Message: Unexpected exception returned from MSAL.

 ---> MSAL.NetCore.4.32.1.0.MsalServiceException:
        ErrorCode: invalid_resource
Microsoft.Identity.Client.MsalServiceException: AADSTS500011: The resource principal named https://graph.microsoft.com was not found in the tenant named 41ebb163-adc1-4068-9087-eb79c718b633. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: aaaf1d24-2664-426f-9ac5-68d828500600
Correlation ID: eb832ea6-c80a-4b32-94ea-ec1631d4c968
Timestamp: 2021-06-18 03:48:17Z
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.HandleTokenRefreshError(MsalServiceException e, MsalAccessTokenCacheItem cachedAccessTokenItem)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Microsoft.Graph.Auth.ClientCredentialProvider.AuthenticateRequestAsync(HttpRequestMessage httpRequestMessage)
        StatusCode: 400
        ResponseBody: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://graph.microsoft.com was not found in the tenant named 41ebb163-adc1-4068-9087-eb79c718b633. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: aaaf1d24-2664-426f-9ac5-68d828500600\r\nCorrelation ID: eb832ea6-c80a-4b32-94ea-ec1631d4c968\r\nTimestamp: 2021-06-18 03:48:17Z","error_codes":[500011],"timestamp":"2021-06-18 03:48:17Z","trace_id":"aaaf1d24-2664-426f-9ac5-68d828500600","correlation_id":"eb832ea6-c80a-4b32-94ea-ec1631d4c968","error_uri":"https://login.partner.microsoftonline.cn/error?code=500011"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: eb832ea6-c80a-4b32-94ea-ec1631d4c968
x-ms-request-id: aaaf1d24-2664-426f-9ac5-68d828500600
x-ms-ests-server: 2.1.11829.4 - CNE2LR2 ProdSlices
x-ms-clitelem: 1,500011,0,,
Set-Cookie: fpc=AvpBlkvJEd9PljBmll_-GziY1pmJAQAAAIEOXtgOAAAA; expires=Sun, 18-Jul-2021 03:48:17 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=productionb; path=/; secure; httponly, stsservicecookie=estschina; path=/; secure; httponly
Date: Fri, 18 Jun 2021 03:48:17 GMT

 
[AB#9950](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9950)

**Comment by andrueastman** [comment]
@KallerLong1 Are you able to confirm if the application with the id `config.AppId` is registered in the same tenant as `config.TenantId`?
