### ISSUE TITLE
Passing in an instance of IBaseRequest which has a request body leaves out request information

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet-core#276]
When passing in an instance of IBaseRequest to send a batch request, some information is left out causing the call to fail.
We need to investigate this and provide a fix.

This is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1038 
[AB#10230](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10230)

**Comment by maisarissi** [comment]
This will come with Kiota version.

**Comment by andrueastman** [comment]
Closing this one for now as this is now covered in Kiota based SDK versions with the introduction of the RequestInformation class which does not leave out information when converted to a HttpRequestMessage instance.

This is supported in the new previews as described in upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#batch-requests).
