### ISSUE TITLE
Sporadic deadlock

### ISSUE THREAD

**Issue by mhs-insiders** [microsoftgraph/msgraph-sdk-dotnet-core#277]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

Hi, we sometimes get a deadlock while listing emails in a folder. Do you have an idea what could cause this?
We are using VisualStudio 2017, .NET Framework 4.8, Microsoft.Graph v4.0.0-preview.7 and Microsoft.Graph.Core v.2.0.0-preview.13.
We also tried it with Microsoft.Graph.Core v2.0.0-preview.14 but it still happend.

### Expected behavior
No deadlocks

### Actual behavior
Sporadic deadlocks, sometimes we seem to get a `System.Threading.Tasks.TaskCanceledException`, other times it works fine.
We first encountered a lot more Deadlocks, when calling the code below in synchronized matter (`.Result` instead of `await`).
We now changed everything to run asynchronously but still get occasional deadlocks when running performance tests.
I'm afraid in heavy load production this will happen a lot more, making our application inoperable.

### Steps to reproduce the behavior
```
GraphServiceClient client = ...;
var request = client.Users[<User>].MailFolders[<Folder>].Messages.Request().Top(100)
        .Expand("microsoft.graph.message/attachments," +
                      "singleValueExtendedProperties($filter=Id eq '" + EmailSchema.Size + "')")
        .Header("Prefer", @"outlook.body-content-type=""html""")
        .Filter(CreateStateFilter(state))
        .OrderBy("receivedDateTime");
 Log.Message("Fetch mails");
 IMailFolderMessagesCollectionPage resultPage = await request.GetAsync();
 Log.Message("Fetch mails finished");
```

 
[AB#10231](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10231)

**Comment by andrueastman** [comment]
Hey @mhs-insiders,

Thanks for raising this. To help us understand this better, are you able to replicate this issue when you downgrade to latest 3.x.x version of the SDK?

**Comment by mhs-insiders** [comment]
Our project is not compatible with 3.x.x. We get a dependency issue with NewtonSoft.Jsons. That's why we used the preview version.

**Comment by andrueastman** [comment]
Thanks for the info. To help us get more information about where the problem could be, are you able to follow the instructions at link below to figure out if the issue when the request is sent out or after the response is received. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/docs/logging-requests.md
