### ISSUE TITLE
Incorrect task cancellation

### ISSUE THREAD

**Issue by 23W** [microsoftgraph/msgraph-sdk-dotnet-core#28]
I use Microsoft Graph C# SDK for managing OneDrive files. My code works with storage in parallel (max thread count < 6). For canceling an operation that is not valid anymore (user closes window or browses to another folder), I use a CancellationToken.

From time to time I receive a `Microsoft.Graph.ServiceException` with the the code `Error.Code = GraphErrorCode`.Timeout instead of `OperationCanceledException` when canceled tasks. 

Your code contains bug in `HttpProvider.SendRequestAsync` method. This method blocks propagation `OperationCanceledException` exception.

For more details please look at [StackOverflow question](https://stackoverflow.com/q/47890382/987850) and [my answer](https://stackoverflow.com/a/47900445/987850) on it.

How to fix it: You should remove `catch (TaskCanceledException exception)` block from `HttpProvider.SendRequestAsync` method.

**Comment by andrueastman** [comment]
Closed via #109
