### ISSUE TITLE
Add real batch support

### ISSUE THREAD

**Issue by habex-ch** [microsoftgraph/msgraph-sdk-dotnet-core#29]
The current implementation for the batch-requests is a nice helper for writting my own HttpClient-Batch-Request, but is far of a real batch support as it was descriped by  @darrelmiller in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/136#issuecomment-411784419. 

For example I have to add 600 users to a group (https://docs.microsoft.com/en-us/graph/api/group-post-members). Unfortunately, there is no API, which supports this. So I have to send 600 requests. 

With the current batch-request implementation I have to
1. Create a JObject for each new member: (new JObject { { "@odata.id", $"https://graph.microsoft.com/v1.0/directoryObjects/{memberId}" } })
2. Create my own HttpRequestMessage objects
3. Add my HttpRequestMessage objects to BatchRequestSteps
4. Bundle those BatchRequestSteps into multiple BatchRequestContent (because only 20 requests per BatchRequestContent are allowed)
5. Create for each BatchRequestContent  another HttpRequestMessage
6. Create an HttpClient (don't forget authentication)
7. Send the HttpRequestMessages of the batch-requests
8. Get the BatchResponseContent from the HttpResponseMessage
9.  Get the HttpResponseMessage for each single request
10. Interpret the responses
11. And so on

I would expect something like @darrelmiller  has described:
```
string groupId = ...
IList<DirectoryObject> newMembers = ...
var batch= new BatchRequestContent();
foreach (var newMember in newMembers)
{
    batch.Add(graphClient.Groups[groupId].Members.References.Request().Add(newMember))
}
var results = graphClient.Batch(batch).Request().ExecuteAsync();
```
Considerations:
A) 
batch.Add() could have a second parameter and third parameter for a specific "requestId" and "dependsOn".
Like Add<TEntity>(TEntity, string requestId = null, string[] dependsOn = null)
If none of them are set, the BatchRequestContent should set its own requestId (e.g. a counter++)

B)
The results should be in the same order as the request were.

C)
If there are more than 20 Requests, the batch should handle them itself

D)
If there would be response-content of e.g. type "User", the results could be interpreted like this:
```
...
if(results.IsSuccessStatusCode)
{
    foreach(var result = batch.Items)
    {
        try
        {
            //result.Get<>() should call throw an exception as graphClient.Groups[groupId].Members.References.Request().AddAsync(newMember);
            User addedUser = result.Get<User>(); 
        }
        catch(Exception ex)
        {
            Logger.LogError(ex, "Couldn't add user to group");
        }
    }
}
``` 
[AB#7195](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7195)

**Comment by darrelmiller** [comment]
It doesn't have to be before the Request(), but I just want to find the most natural syntax.

**Comment by habex-ch** [comment]
I think most natural would be 
`graphClient.Groups[groupId].Members.References.Request().Add(newMember).GetHttpRequestMessage()`

**Comment by praveenlearns** [comment]
I am new to graph apis and looking for creating group calendar events in bulk (batch) using graph apis. Is there a workaround to achieve something like this? 

_graphServiceClient.Groups[userGroupId].Events.Request().AddAsync(@eventList);

**Comment by habex-ch** [comment]
@praveenlearns 
I have described the current batch implementation in my first post. Did you try that?

**Comment by darrelmiller** [comment]
Created an issue to address the ability to create Requests with a body to add to batches.  https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/229

**Comment by maisarissi** [comment]
Hello everyone.

As part of the new core v3 version, we do have the ability of creating requests with a body to add to batches. This can be accomplished by using [RequestInformation](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#use-of-requestinformation-from-kiota-in-place-of-ibaserequest) as the following:

```csharp
var graphClient = new GraphServiceClient(...);

// Create a BatchRequestContent
var batchRequestContent = new BatchRequestContent(graphClient);

// Add requests to it, max of 20
var usersRequest= await batchRequestContent.AddBatchRequestStepAsync(graphClient.Me.ToGetRequestInformation());
var eventsRequest = graphClient.Me.CalendarView
    .ToGetRequestInformation(requestConfiguration => 
        {
            requestConfiguration.QueryParameters.StartDateTime = today.ToString("yyyy-MM-ddTHH:mm:ssK");
            requestConfiguration.QueryParameters.EndDateTime = today.AddDays(1).ToString("yyyy-MM-ddTHH:mm:ssK");
        });

//Using AddBatchRequestStepAsync adds each request as a step
//No specified order of execution
var userRequestId = await batchRequestContent.AddBatchRequestStepAsync(userRequest);
var eventsRequestId = await batchRequestContent.AddBatchRequestStepAsync(eventsRequest);

// Execute the batch request
var response = await graphClient.Batch.PostAsync(batchRequestContent);

// De-serialize response based on known return type
try
{
    var user = await returnedResponse
        .GetResponseByIdAsync<User>(userRequestId);
    Console.WriteLine($"Hello {user.DisplayName}!");
}
catch (ServiceException ex)
{
    Console.WriteLine($"Get user failed: {ex.Error.Message}");
}
```

This is pretty similar to what was described by Darrel in the comment mentioned in the description of this issue.
We are closing this as we believe the initial request has been reached.

The next step is to evaluate improving batching support to handle the limit of 20 requests tracked by https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/612

**Comment by svrooij** [comment]
@habex-ch I got you covered, adding 400 users to a group in 1 http call... Want to give it a go? 

https://svrooij.io/2023/03/03/batching-in-microsoft-graph/#adding-400-users-to-a-group
