### ISSUE TITLE
Batch request does not work with SendMail

### ISSUE THREAD

**Issue by mikequ-taggysoft** [microsoftgraph/msgraph-sdk-dotnet-core#294]
My goal is to use the Graph .NET SDK to send multiple emails individually to a list of addresses. I do not want to put all addresses in `ToRecipients`  because the recipients would see other people's emails which is against the business requirements.  We cannot use BCC either because it would not display each user in the To field properly. 

We can surely achieve this by sending individual `SendMail` requests in a loop. But to save unnecessary API trips, I want to use the MS Graph SDK's batch feature.

### Expected behavior

Multiple `IUserSendMailRequest` added to `BatchRequestContent` should be able to send multiple emails in a batch.

### Actual behavior

Emails are not sent. No exceptions or error messages. Without the batch, individual requests work perfectly. 

### Steps to reproduce the behavior

Below are my codes:

```
var batchRequestContent = new BatchRequestContent();

foreach (var toAddress in toAddresses)
{
    var message = new Message
    {
        Subject = subject,
        Body = new ItemBody
        {
            ContentType = BodyType.Html,
            Content = body
         },
         ToRecipients = new List<Recipient>() { new Recipient { EmailAddress = new EmailAddress { Address = toAddress } } 
    };
             
    var request = _graphClient.Me.SendMail(message, true).Request();

    batchRequestContent.AddBatchRequestStep(request);
}

await _graphClient.Batch.Request().PostAsync(batchRequestContent);
```

 
[AB#10419](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10419)

**Comment by andrueastman** [comment]
Thanks for raising this issue @mikequ-taggysoft.

The issue you are experiencing is currently related to #276.

At the moment you should be able to work around this by using the following workaround as we work towards fixing the issue in the SDK.

```cs
var batchRequestContent = new BatchRequestContent();

foreach (var toAddress in toAddresses)
{
    var message = new Message
    {
        Subject = subject,
        Body = new ItemBody
        {
            ContentType = BodyType.Html,
            Content = body
         },
         ToRecipients = new List<Recipient>() { new Recipient { EmailAddress = new EmailAddress { Address = toAddress } } 
    };
             
    var request = _graphClient.Me.SendMail(message, true).Request();

    // Add this lines
    var httpRequestMessage = request.GetHttpRequestMessage();
    httpRequestMessage.Method = HttpMethod.Post; // "POST" for V3 and below of SDK
    httpRequestMessage.Content = new StringContent(graphClient.HttpProvider.Serializer.SerializeObject(request.RequestBody));
    httpRequestMessage.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");

    batchRequestContent.AddBatchRequestStep(httpRequestMessage);
}

await _graphClient.Batch.Request().PostAsync(batchRequestContent);
```

**Comment by mikequ-taggysoft** [comment]
Thanks @andrueastman The workaround works perfectly. Looking forward to the permanent fix.
