### ISSUE TITLE
Support setting null on properties

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#30]
The Microsoft Graph service shouldn't be serializing properties with null values. But, in the case that it does, the client deserializes those properties into AdditionalData. I'm trying to figure out of this is a feature or a bug.
The service should only send null values if the value has been set to null, and only as part of a delta.
It is a feature as it would support the service in specifying that a properties value has been set to null. We really haven't worked out the null story.
It is a bug when the service erroneously sends a bunch of null values.
[AB#6148](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6148)

**Comment by MIchaelMainer** [comment]
* Set null on schematized properties generated into our models. (currently supported via AdditionalData)
* Set null on non-schematized properties. (currently supported via AdditionalData)
* Discover null set on schematized properties generated into our models
* Discover null set on non-schematized properties. (currently supported via AdditionalData) 

Validate against both .NET Core and .NET Framework scenarios.

**Comment by maisarissi** [comment]
This will come with the backing store feature on the new version through Kiota.

**Comment by andrueastman** [comment]
Closing this one for now. 

Backing Store feature has now been enabled in the latest V5 previews of the SDK and information can be found in [this ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#backing-store)section of the upgrade guide.
