### ISSUE TITLE
Serializer checking for Length without consulting the CanSeek boolean

### ISSUE THREAD

**Issue by Dethras** [microsoftgraph/msgraph-sdk-dotnet-core#311]
I am having an issue, were I am trying to deserialize a GZipStream containing the Microsoft.Graph.ErrorResponse object from a graph call response object. The serializer is checking for the "Length" and throwing since the GZipStream doesn't support it. Should the serializer at least check for the CanSeek?, or better yet skip the "Length" check, since a lot of streams work without having the support for the "Length" property.

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/00c0749d7332b753c51051f5158c2d587557b52f/src/Microsoft.Graph.Core/Serialization/Serializer.cs#L51 
[AB#10925](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10925)

**Comment by andrueastman** [comment]
Hey @Dethras, 

Thanks for raising this issue. Are you able to provide more information (code sample) about how you are passing the stream to the serializer?

I believe the [CompressionHandler](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/00c0749d7332b753c51051f5158c2d587557b52f/src/Microsoft.Graph.Core/Requests/Middleware/CompressionHandler.cs#L57) should be decompressing GZipStreams to enable the stream to be read as expected.

**Comment by Dethras** [comment]
@andrueastman 

so the following code is called when we catch an exception from any graph call. The idea is to deserialize the response into the "Microsoft.Graph.ErrorResponse" Object. In both the if cases when we try to deserialize, the Serializer will throw a NotSupportedException for trying to access the length.


```
if (response.Content.Headers.ContentEncoding.Contains("gzip"))
{
    using var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
    using var compressedStream = new GZipStream(responseStream, CompressionMode.Decompress);

    return _serializer.DeserializeObject<ErrorResponse>(compressedStream);
}
else 
{
    using var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);

    return _serializer.DeserializeObject<ErrorResponse>(stream);
}
```

**Comment by andrueastman** [comment]
Does that mean that you are making requests with a custom HttpClient?

Since the CompressionHandler is already part of the http middleware, the response content should already come back decompressed if the gzip header is present and there would be no need for the check you are trying to make. Yes?

**Comment by Dethras** [comment]
@andrueastman 

It depends what you mean by custom HttpClient, I am creating one using the GraphClientFactory, and I have a series of custom handlers that I am using. Not sure if the GraphClientFactory.Create, injects the CompressionHandler in there as well, but I would assume that it doesn't.

```
var authProvider = new GraphAuthenticationProvider(azureTokenAuthentication);
var httpClient = GraphClientFactory.Create(authProvider, finalHandler: finalHandler);

_graphClient = new GraphServiceClient(httpClient);
```

**Comment by andrueastman** [comment]
According to [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/00c0749d7332b753c51051f5158c2d587557b52f/src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs#L125), the code you provided should add the CompressionHandler by default and there shouldn't be a need to check the compression header.

Are you experiencing something different? If so, are you able to provide the version of Microsoft.Graph.Core you are using?

**Comment by Dethras** [comment]
@andrueastman, Yes the issue is that when handling a response the CompressionHandler is the last handler that will take action. In my case another handler is doing that code above, so the data is not decompressed yet. 

Having said that, after seeing how the HttpClient is actually created, I will change my implementation by creating the default graph handlers myself and insert them in my delegated handler list  in which order I need them, this will solve my problem.

Thanks a lot for the information :)
