### ISSUE TITLE
Problem with Microsoft.GraphCore.HttpProvider.Serializer and number to string conversion

### ISSUE THREAD

**Issue by Mogikan** [microsoftgraph/msgraph-sdk-dotnet-core#319]
I use the following repo and it uses Graph.Core. Unfortunately this repo is dead and I support it myself since I use it in xamarin project and cannot use old unsupported libraries.
[One drive SDK](https://github.com/OneDrive/onedrive-sdk-csharp)

As I can see you updated to the new serializer. I fixed almost all the issues, but there is one which should be fixed on your side:
In the OAuthHelper of the One drive sdk there is the following code:
```
public async Task<AccountSession> SendTokenRequestAsync(string requestBodyString, IHttpProvider httpProvider)
        {
            var httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, OAuthConstants.MicrosoftAccountTokenServiceUrl);

            httpRequestMessage.Content = new StringContent(requestBodyString, Encoding.UTF8, "application/x-www-form-urlencoded");

            using (var authResponse = await httpProvider.SendAsync(httpRequestMessage).ConfigureAwait(false))
            using (var responseStream = await authResponse.Content.ReadAsStreamAsync().ConfigureAwait(false))
            {
                **var responseValues =
                    httpProvider.Serializer.DeserializeObject<IDictionary<string, string>>(
                        responseStream);**
```

It uses your serializer from GraphCore, but it receives the following json in responseStream and it worked fine with Newtonsoft.Json, but fails with System.Text.Json:
```
{
  "token_type":"bearer",
  "expires_in": 3600,
  "scope":"wl.basic onedrive.readwrite",
  "access_token":"EwCo...AA==",
  "refresh_token":"eyJh...9323"
}
```

And it fails on the iPhone (xamarin.iOS) to deserialize 3600 into string.

And I couldn't pass additional settings to serializer. Maybe you can add additional converter to your serializer which can convert numbers to string when required? Since otherwise I suppose a lot of work may appear in similar cases like in the one I described.
https://stackoverflow.com/a/59099589

**Comment by andrueastman** [comment]
Hey @Mogikan,

Thanks for raising this issue. 

Are you able to share how you tried to pass the additional settings to the Serializer?

**Comment by andrueastman** [comment]
I believe you should be able to use custom serializer options as follows,

```cs
var serializer = new Serializer(new JsonSerializerOptions()
{
    Converters = { new MyCustomConverter() }
}); // pass custom serializer options
var httpProvider = new HttpProvider(serializer);
var client = new GraphServiceClient(usernamePasswordCredential, scopes, httpProvider);
```

**Comment by Mogikan** [comment]
@andrueastman 
I expected your serializer will have similar API like the one available here:
[Desirialize members of JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserialize?view=net-5.0)
* httpProvider.Serializer.DeserializeObject<IDictionary<string, string>>(responseStream, **SETTINGSHERE**);
I do not create serializer, it's created by httpprovider and didn't know that httpprovider has such ctor.

**Comment by andrueastman** [comment]
Hey @Mogikan,
I believe, the `Serializer` class is meant to be a default implementation of the [`ISerializer`](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Serialization/ISerializer.cs)interface (which happens to use System.Text.Json in this case). This is so that if a user may wish to use a different serialization library with the client, they would just implement the interface and pass it to the client. Changing the function signature may break the interface contract.

Since the call to `httpProvider.Serializer.DeserializeObject` just ends up calling System.Text.Json, I believe for your case you should be able to just call the serializer directly as below.

```cs
var responseValues = JsonSerializer.DeserializeAsync<IDictionary<string, string>>(stream, customJsonSerializerOptions);
```

**Comment by Mogikan** [comment]
OK, thanks, I've got your point. Seems like I could have used NewtonSoft json without modifing lots of code on the client. But anyway, thanks. Currently I decided to deserialize it to IDictionary<string,object> and then turn it into IDictionary<string,string>.

**Comment by andrueastman** [comment]
No worries @Mogikan.

Closing this for now. Feel free to open a new issue if anything else comes up
