### ISSUE TITLE
ResponseHandler should look at Content-Type before trying to deserialize as JSON

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-dotnet-core#32]
See https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/534

We should only pass content on to the Serializer if the content-Type is `application/json` otherwise we need to find some other way of returning the payload.

This is going to need to be fixed in the snippet generator as this is wrong https://docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-1.0&tabs=csharp#request
 
[AB#7197](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7197)

**Comment by andrueastman** [comment]
This should be resolved with Kiota as the `ParseNodeRegistry` uses the `Content-Type` to determine the factory to use to handle the response.

Ref [here](https://github.com/microsoft/kiota/blob/81693dd7b4b68a62dbc600c1286d01e92c0a05b6/abstractions/dotnet/src/serialization/ParseNodeFactoryRegistry.cs#L46)

**Comment by andrueastman** [comment]
Closing this now as this is validated with the latest kiota based preview versions
