### ISSUE TITLE
Use MSAL JSON - remove Newtonsoft dependency

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#33]
This work has to happen after #25, moving auth providers to core.

**Comment by andrueastman** [comment]
It looks like the code [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/master/src/client/Microsoft.Identity.Client/json) is internal to the lib and not exposed.

**Comment by darrelmiller** [comment]
As we cannot using JSON.NET in MSAL, we are looking into using System.Text.JSON #74
