### ISSUE TITLE
Problem using collection paging with Microsoft.Graph.Core 2.0.6

### ISSUE THREAD

**Issue by stefanboerner** [microsoftgraph/msgraph-sdk-dotnet-core#345]
### Expected behavior
IGraphService...CollectionPage.NextPageRequest should contain only valid queryOptions

### Actual behavior
First Queryoption name is invalid ?$top instead of $top which leads to errors when sending the request for the 2nd page.

### Steps to reproduce the behavior
Use Microsoft.Graph 4.11 and Microsoft.Graph.Core 2.0.6 libraries in our app to query data as follows: 

```
var groups = new List<Group>();
var req = Context.GraphClient.Groups.Request().Top(500).Select("Id,DisplayName");
var firstPage = req.GetAsync().Result;
groups.AddRange(firstPage.CurrentPage);

  IGraphServiceGroupsCollectionPage current = firstPage;
  while (current.NextPageRequest != null)
  {
	  // the following 'NextPageRequest' request fails
	  // current.NextPageRequest.QueryOptions[0].Name is "?$top" instead of "$top"
  
	  current = current.NextPageRequest.GetAsync().Result;
	  groups.AddRange(current.CurrentPage);
  }
```

Error:
Microsoft.Graph.ServiceException: 'Code: Request_BadRequest
Message: Unrecognized query argument specified: '?$top'.

If we remove "?" in front of "$top" the request is successful executed.
When using Microsoft.Graph.Core 2.0.5. everything is fine.

**Comment by andrueastman** [comment]
Hey @stefanboerner,

Thanks for raising this. 

Unfortunately, I am unable to replicate this issue. Are you able to provide more information about the runtime you are using to help us understand the issue better?

Also, are you able to replicate this with the new 4.12.0 package?

**Comment by stefanboerner** [comment]
Hey @andrueastman 

The target framework of the app ist .NET Framework 4.7.2
A test with the following references
- Microsoft.Graph 4.12.0
- Microsoft.Graph.Core **2.0.6**
resulted with the same error.

Another test with the following references
- Microsoft.Graph 4.12.0
- Microsoft.Graph.Core **2.0.5**
did not result in an error

**Comment by andrueastman** [comment]
Thanks for the information @stefanboerner.

It looks like the issue only affects .Net Framework environments due to how the runtime handles the Query parameter given the change made in 2.0.6 as explained [here](https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.query?view=net-6.0#remarks).

We are working towards having this resolved and will have a fix out asap.
