### ISSUE TITLE
A developer can integrate OpenTelemetry observability with the .NET SDK

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#35]
[AB#6090](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6090)

**Comment by maisarissi** [comment]
First PR for observability spec: https://github.com/microsoftgraph/msgraph-sdk-design/pull/72
