### ISSUE TITLE
Filtering document libraries by display name contained symbol ' (apostrophe)

### ISSUE THREAD

**Issue by rememberDL** [microsoftgraph/msgraph-sdk-dotnet-core#351]
### Expected behavior
Using MS Graph we can create a document library with display name contained symbol ' (apostrophe). 
According to expected behavior the filter clauses should return created library.

### Actual behavior
We get error:

Code: BadRequest
Message: Invalid filter clause

### Steps to reproduce the behavior
ms graph version 4.11.0
C# .Net 4.6.2
```csharp
// list creation is successful
var listTitle = "Test's test"; 
var list = new List 
{
  DisplayName = listTitle, 
  ListInfo = new ListInfo{Template = "documentLibrary",ContentTypesEnabled   = true} 
}; 
var listCreated = await graph.Sites[siteId].Lists.Request().AddAsync(list).ConfigureAwait(false); 

var lists = await graph.Sites[siteId].Lists.Request().Filter($"DisplayName eq '{listTitle}'").GetAsync().ConfigureAwait(false); 
```

**Comment by zengin** [comment]
@rememberDL please escape the single quote in the string literal according to OData escaping rules: https://docs.microsoft.com/en-us/azure/search/query-odata-filter-orderby-syntax#escaping-special-characters-in-string-constants

This is only needed in the query string parameters such as filter because of the special meaning of single quotes in that context, escaping is not needed while creating the object.

**Comment by rememberDL** [comment]
@zengin thank you for the answer, but for me it does not work. I checked requests by Fiddler, the result is 
![image](https://user-images.githubusercontent.com/55530857/149726664-b575ef5a-f6cc-4d44-9bc6-5839e452e842.png)

```csharp
   if (listTitle.Contains("'"))
   {
       listTitle = listTitle.Replace("'", "''");
   }
   var lists = await graph.Sites[siteId].Lists.Request().Filter($"DisplayName eq '{listTitle}'").GetAsync().ConfigureAwait(false);
```

**Comment by zengin** [comment]
@rememberDL I don't see the `s` after the apostrophe in your Fiddler screenshot. Could you please double check the `listTitle` value at the time of the call?

---
Expected
```
lists?$filter=DisplayName%20eq%20%27Test%27%27s%20test%27
```
vs Actual
```
lists?$filter=DisplayName%20eq%20%27Test%27%27%20test%27
```
---
**URL decoded:**
Expected
```
lists?$filter=DisplayName eq 'Test''s test'
```
vs Actual
```
lists?$filter=DisplayName eq 'Test'' test'
```

**Comment by rememberDL** [comment]
@zengin, sorry for the mistake and thanks a lot for the solution
