### ISSUE TITLE
Upload large attachment .cs code is not updated. 

### ISSUE THREAD

**Issue by R-LIBIN** [microsoftgraph/msgraph-sdk-dotnet-core#353]
Please include the code update required data. 

### Expected behavior

URL : https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp

### Actual behavior

Code is expected with proper explanation. 

### Steps to reproduce the behavior

Need the code with native glaph client api.

**Comment by andrueastman** [comment]
Hey @R-LIBIN,

Thanks for raising this. 

Any chance you could provide more information on what exactly is missing in the docs?

**Comment by R-LIBIN** [comment]
URL : https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp 

![image](https://user-images.githubusercontent.com/16919701/149419493-8e5c2a4d-75ba-4ec9-b240-2bd5c8abadf3.png)

Also, Java is not updated. for me, I need .Net that too .net 6

**Comment by R-LIBIN** [comment]
Need the three steps of uploading to upload session one single code. That would be better. Especially, with graphClient API. 

Eg. graphClient.User[]......ExecuteAsync. 

Please do implement all three this increases abreaction.

**Comment by R-LIBIN** [comment]
*   abstaction. 

All we need is message Id with we can offer. Also, same for event.

**Comment by R-LIBIN** [comment]
All should go in backend. This, it seems has been released for about 2 years ago yet hasn't enhanced yet being set of simple statements of code.

**Comment by R-LIBIN** [comment]
Additionally(personal use.). temporarily, Please provide me the code to upload excel file from scratch that is read as ReadAllBytes() function which returns bytes.

It is for personal use. help me. Please help me. I feel microdoft too abstract with very less code snippets. Please take it further. These are very help. This can take things too far. far ahead. far ahead of any of time. Thank you. 

This is a temporary code. I am trying for this. Also, 

As of Now, Please find the code..  I get the code, 

var FilePath = "{System Path}//file"; 

        byte[] readText = System.IO.File.ReadAllBytes(FilePath);

        
        var request = new HttpRequestMessage(HttpMethod.Put, endpoint);

        var content = Convert.ToBase64String(readText.ToArray());;



        request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/octet-stream"));
        request.Content = new StringContent(content, Encoding.ASCII);
        request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
        request.Content.Headers.ContentLength = readText.Length;
        var response = await new HttpClient().SendAsync(request);
        response.EnsureSuccessStatusCode();

        if (response.IsSuccessStatusCode)
        {
            // The ItemResponse object in the result represents the
            // created item.
            Console.WriteLine($"Upload complete, item ID: {response.ReasonPhrase}");
        }
        else
        {
            Console.WriteLine("Upload failed");
        }

Error: {"error":{"code":"ErrorInvalidRequest","message":"The OData request is not supported."}}

**Comment by R-LIBIN** [comment]
![image](https://user-images.githubusercontent.com/16919701/149421428-400f424b-2b53-4d10-9990-b89f0b4cb0f2.png)

request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/octet-stream"));
    request.Content = new StringContent(content, Encoding.ASCII);
    request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
    request.Content.Headers.ContentLength = readText.Length;

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/microsoft-graph-docs/pull/15897
