### ISSUE TITLE
HTTP/2 validation

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-dotnet-core#357]
AGS is rolling out HTTP/2 support. It is already available in Canary.

The goal here is to test our current client against Canary to validate that it's using http2 when available and there's no issues related to http.2 (response header casing etc.)

Details to connect to Canary are available on the dedicated Teams discussion.

**Comment by andrueastman** [comment]
As is, as we do not set the HttpRequestMessage.Version property (ref [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/6ec55dcc43b884cec3d61aeb3ceb69fe27852157/src/Microsoft.Graph.Core/Requests/BaseRequest.cs#L304) ) when creating the request message object, this means therefore that the http requests will be made as HTTP 1.1 requests (unless one is running .Net core 2.1/2.2 ref [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.version?view=net-6.0#remarks)). 

If we wish to force/default to Http/2 we would need to do some refactoring there (or maybe add a handler that changes the version property?) as the underlying HttpClient will respect the version property of the HttpRequestMessage object (unless we modify the [HttpClient.DefaultRequestVersion](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestversion?view=net-6.0#definition) property but this property is available on only some select runtimes). 

Recent versions of dotnet (dotnet 5 and 6) also provide [HttpRequestMessage.VersionPolicy](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpversionpolicy?view=net-6.0) property that allows one to configure the fallback behavior but this is not the currently targeted runtime by the SDK. Furthermore, this would need to be explicitly set to a value correlated with the HTTP Version as the default enum value (RequestVersionOrLower) together with the default HTTP Version will still result to HTTP1.1 requests being made.
