### ISSUE TITLE
Me.Memberof does not deliver all properties that are available in GraphExplorer

### ISSUE THREAD

**Issue by ckoch1979silentservice** [microsoftgraph/msgraph-sdk-dotnet-core#360]
### Expected behavior

All properties of the member objects should be delivered. Graph explorer (direct api call) offers the following properties:

            "@odata.type": 
            "id": 
            "deletedDateTime": 
            "classification":
            "createdDateTime": 
            "creationOptions":
            "description":
            "displayName": 
            "expirationDateTime": 
            "groupTypes":
            "isAssignableToRole":
            "mail": 
            "mailEnabled": 
            "mailNickname": 
            "membershipRule": 
            "membershipRuleProcessingState": 
            "onPremisesDomainName": 
            "onPremisesLastSyncDateTime": 
            "onPremisesNetBiosName": 
            "onPremisesSamAccountName": 
            "onPremisesSecurityIdentifier": 
            "onPremisesSyncEnabled": 
            "preferredDataLocation": 
            "preferredLanguage": 
            "proxyAddresses": 
            "renewedDateTime": 
            "resourceBehaviorOptions":
            "resourceProvisioningOptions": 
            "securityEnabled": 
            "securityIdentifier": "
            "theme":
            "visibility":
            "onPremisesProvisioningErrors":

### Actual behavior

Only these properties are available:

ODataType
Id
DeletedDateTime
AdditionalData

### Steps to reproduce the behavior

Just call 

`await _graphServiceClient.Me.MemberOf.Request().GetAsync();`

... and check the offered properties on intellisense

**Comment by andrueastman** [comment]
Hey @ckoch1979silentservice,

Thanks for raising this. Any chance you can provide more details about the version of the client SDK you are using to replicate this scenario?

**Comment by ckoch1979silentservice** [comment]
The most recent - 2.07!

**Comment by ckoch1979silentservice** [comment]
Another remark: This behavior is seen with MemberOf and TransitiveMemberOf

**Comment by andrueastman** [comment]
Are you by any chance using the core library package by itself? Or do you also use one of the service libraries ([v1](https://www.nuget.org/packages/Microsoft.Graph) or [beta](https://www.nuget.org/packages/Microsoft.Graph.Beta))? If so, which package versions are those?

**Comment by ckoch1979silentservice** [comment]
What do you exactly mean with service libraries? I use the v1 endpoint.

**Comment by ckoch1979silentservice** [comment]
I also use

Microsoft.Identity.Web.MicrosoftGraph 1.22.1

**Comment by zengin** [comment]
`memberOf` is a collection of `directoryObject` which is a parent type to types like `directoryRole` and `group`. One way to get intellisense support and access these properties would be like the following:

```csharp
var memberOf = await _graphServiceClient.Me.MemberOf.Request().GetAsync();
foreach(var m in memberOf)
{
	switch (m)
	{
		case Microsoft.Graph.DirectoryRole dr:
		  Console.WriteLine(dr.DisplayName);
		  // Intellisense will give all properties for DirectoryRole objects at this point
		  break;
		case Microsoft.Graph.Group g:
		  Console.WriteLine(g.DisplayName);
		  break;
		default:
		  break;
	}
}
```

or 

```csharp
foreach(var m in memberOf)
{
	if (m is DirectoryRole dr)
	{
		Console.WriteLine(dr.DisplayName);
	}
}
```

or

```csharp
foreach(var m in memberOf)
{
	Console.WriteLine((m as DirectoryRole)?.DisplayName);
}
```

From an SDK design perspective, generated parent types don't hold properties from the child types directly in order to avoid a huge expansion of the package size. Instead, we rely on generics and type hierarchies.

**Comment by maisarissi** [comment]
Hi @ckoch1979silentservice .

The core library is responsible for providing a set of features that enhance working with Microsoft Graph, such as retry, redirect, transparent auth and more. The service library takes dependency of the core library and its features and provides models and request builders.
You can find more information [here](https://docs.microsoft.com/en-us/graph/sdks/sdks-overview?context=graph%2Fapi%2F1.0&view=graph-rest-1.0).

> Microsoft.Graph 4.11.0

Per your comment, it seems like you have the service library installed, the [Microsoft.Graph](https://www.nuget.org/packages/Microsoft.Graph) package. The [Microsoft.Graph.Core](https://www.nuget.org/packages/Microsoft.Graph.Core) package is related to the core library.

Is the comment shared by @zengin helpful?
