### ISSUE TITLE
Passing handlers to GraphClientFactory.Create() creates a HttpClient that disposes the handlers

### ISSUE THREAD

**Issue by agehrke** [microsoftgraph/msgraph-sdk-dotnet-core#373]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Documentation of [GraphClientFactory.Create()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.graph.graphclientfactory.create?view=graph-core-dotnet#microsoft-graph-graphclientfactory-create(system-collections-generic-ienumerable((system-net-http-delegatinghandler))-system-string-system-string-system-net-iwebproxy-system-net-http-httpmessagehandler)) method does not describe disposal of passed handlers, eg the collection of `DelegatingHandler` and optional `finalHandler`.

IMO, passing disposable objects to another object does not imply that the receiving object can take ownership of those disposable objects. However changing the behavior is breaking, and adding an additional optional argument to control dispose behavior may not be desirable. So maybe this is basically just a documentation issue.

### Actual behavior
Currently the method creates a `HttpClient` that disposes its `HttpMessageHandler` and thus the collection of `DelegatingHandler` and optional `finalHandler` as the `HttpClient` is created without specifying the `bool disposeHandler` parameter.

### Steps to reproduce the behavior
A test that shows finalHandler is disposed:

```csharp
[Fact]
public void CreateClient_WithFinalHandlerDisposesTheFinalHandler()
{
    var finalHandler = new MockHttpHandler();
    using (HttpClient client = GraphClientFactory.Create(handlers: GraphClientFactory.CreateDefaultHandlers(testAuthenticationProvider.Object), finalHandler: finalHandler))
    {
        Assert.NotNull(client);
    }

    Assert.True(finalHandler.Disposed);
}

private class MockHttpHandler : HttpMessageHandler
{
    public bool Disposed;

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }

    protected override void Dispose(bool disposing)
    {
        Disposed = true;
        base.Dispose(disposing);
    }
}
```

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/486
