### ISSUE TITLE
Can we get a .sln file that doesn't require the Xamarin SDK installed?

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-dotnet-core#39]
It's not very friendly to require that the Android SDK is installed to open the solution.  Also, we should provide installation instructions in the readme as to what Android related SDKs do need to be installed. 
[AB#7198](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7198)

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/486
