### ISSUE TITLE
Unable to differentiate between a no change and a change to null when changes occur.

### ISSUE THREAD

**Issue by gastart** [microsoftgraph/msgraph-sdk-dotnet-core#40]
The client library does not provide a clear way to differentiate between a no change and a change to null when changes occur.

For example when a mail is marked as read the following delta is provided.

```
 {
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(message)",
	"@odata.deltaLink": "https://graph.microsoft.com/v1.0/users/fde0eb6a-2112-4220-85ed-b5712491efc4/mailFolders/AAMkADlmZmQ4M2Y0LTcxY2YtNDUzZi04NjZhLTY4ZDZjZTViMmY1MwAuAAAAAACzDaE9G9XYTb-ZqVQX1BNAAQDfLwJoKP36R76dWMpnXk8WAAAAAAEMAAA=/messages/microsoft.graph.delta?$deltatoken=LztZwWjo5IivWBhyxw5rAEqSrjmAQYZUg8dthzmVkwlXG92TQA-ylvsk2XZaqDw1WzxW0Hi9jaGBTC6LgCLyNEXaHgeG3_V4wT5_nqZSntM.Cuh6VVZ70NIVCZdWuUCvQzTfqHTrNp9N06GSxKUEzoA",
	"value": [{
		"@odata.type": "#microsoft.graph.message",
		"parentFolderId": "AAMkADlmZmQ4M2Y0LTcxY2YtNDUzZi04NjZhLTY4ZDZjZTViMmY1MwAuAAAAAACzDaE9G9XYTb-ZqVQX1BNAAQDfLwJoKP36R76dWMpnXk8WAAAAAAEMAAA=",
		"isRead": false,
		"id": "AAMkADlmZmQ4M2Y0LTcxY2YtNDUzZi04NjZhLTY4ZDZjZTViMmY1MwBGAAAAAACzDaE9G9XYTb-ZqVQX1BNABwDfLwJoKP36R76dWMpnXk8WAAAAAAEMAADfLwJoKP36R76dWMpnXk8WAAAJEOXIAAA=",
		"id": "AAMkADlmZmQ4M2Y0LTcxY2YtNDUzZi04NjZhLTY4ZDZjZTViMmY1MwBGAAAAAACzDaE9G9XYTb-ZqVQX1BNABwDfLwJoKP36R76dWMpnXk8WAAAAAAEMAADfLwJoKP36R76dWMpnXk8WAAAJEOXIAAA="
	}]
}
```

When the json is de-serialized the supplied message object will contain a lot of nulls.
![message_object](https://user-images.githubusercontent.com/13785378/31656086-ee94a240-b32a-11e7-9d04-96c3c48c2c6a.png)

My problem is that via the supplied abstraction I have no concrete way of saying if something changed to null or if something did not change at all.

A solution that comes to mind is to add a property to the message object with a list of the changed fields.
 
[AB#6241](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6241)

**Comment by maisarissi** [comment]
Hi everyone.

This will come with the backing store feature on the new version through Kiota.

**Comment by andrueastman** [comment]
Closing this one for now. 

Backing Store feature has now been enabled in the latest V5 previews of the SDK and information can be found in [this ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#backing-store)section of the upgrade guide.

**Comment by andrueastman** [comment]
Hey @hansShin,

For delta requests specifically, there exists the [DeltaResponseHandler](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/7019da416164884912b8a38f504fd543156867bf/src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs#L22) which you can use and it will add an extra object in the additionalData dictionary with the "changes" key and will list jsonPaths of the changed properties.

You can check out the tests at the link below for reference as well. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/7019da416164884912b8a38f504fd543156867bf/tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs#L177
