### ISSUE TITLE
Remove the ODataQueryParametersHandler

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet-core#406]
For the preview v1 version, once these are merged and the references are updated:
- https://github.com/microsoft/kiota/pull/1498
- https://github.com/microsoft/kiota-http-dotnet/pull/12
- https://github.com/microsoft/kiota-http-dotnet/pull/12

(and once a generation had been triggered)

**Comment by andrueastman** [comment]
Closed via #408
