### ISSUE TITLE
MAUI support

### ISSUE THREAD

**Issue by pekspro** [microsoftgraph/msgraph-sdk-dotnet-core#413]
Currently, this SDK doesn't work well on Android with MAUI, see details here (and a workaround): https://github.com/dotnet/maui/issues/3903

Is there any plans to add support for MAUI?

**Comment by edoust** [comment]
It also does not work on MacCatalyst

**Comment by dm-pr** [comment]
Experiencing the same issue while targeting only Android and Windows in my MAUI app.

Workaround described in issue https://github.com/dotnet/maui/issues/3903  still works, but the conclusion in that thread was that net6. iOS lib was the problem.  I am targeting only Android and Windows and still issue exists.

System.TypeLoadException: 'Could not resolve type with token 01000023 from typeref (expected class 'System.Threading.Tasks.ValueTask`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e')'

This is my test code:

```


var pc = PublicClientApplicationBuilder.Create("--CLIENT--ID--")
		.WithAuthority("https://login.microsoftonline.com/--TENANT--ID--/")
		.WithDefaultRedirectUri()
		.Build();


	var t = await pc.AcquireTokenInteractive(new string[] { "User.Read" })
		.WithPrompt(Microsoft.Identity.Client.Prompt.ForceLogin)
#if ANDROID
		.WithParentActivityOrWindow(Platform.CurrentActivity)
#endif
		.ExecuteAsync();


	var graphClient = new GraphServiceClient("https://graph.microsoft.com/beta", null);


	graphClient.AuthenticationProvider = new DelegateAuthenticationProvider(async (request) => {
		request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", t.AccessToken);
		await Task.FromResult<object>(null);
	});


	var resp = await graphClient.Me.Request().GetAsync();

	uLabel.Text = resp.DisplayName;

```


this code works fine on Windows, but not on Android

**Comment by tipa** [comment]
Hitting the same issue. Any updates on this?

**Comment by maisarissi** [comment]
@andrueastman can you take a look at this issue? Thanks.

**Comment by andrueastman** [comment]
We will be looking into adding the `net6.0-ios` and MAUI build targets in the upcoming preview releases for Kiota.

**Comment by NPadrutt** [comment]
Is there an update or ETA for this?

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/486

**Comment by NPadrutt** [comment]
Is there a preview version for this planne? As far as I can see the latest preview is from last month and does not contain this yet.

**Comment by dvag-ehssan-doust** [comment]
@andrueastman
Is there a planned release date for v5 of the graph sdk for dotnet or any kind of roadmap for the update?

**Comment by edoust** [comment]
@andrueastman 
Is there a planned release date for graph sdk v5 or any kind of roadmap that I could look at to track the progress?

**Comment by maisarissi** [comment]
Hi @NPadrutt . [Microsoft Graph .NET SDK service library 5.0.0-preview.11](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/Microsoft.Graph.5.0.0-preview.11.nupkg) that take advantage of [core 3.0.0-preview.13](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/releases/tag/3.0.0-preview.13) has support for MAUI.

**Comment by NPadrutt** [comment]
@maisarissi thanks for the info. I actually tried to already update to the preview but it broke my WinUI app with weird build issues. 
Given that and that I was blocked by the lack of MAUI support I went the route of replacing the Graph SDK and just consume the API directly.

**Comment by maisarissi** [comment]
We would love to get any feedback you might have after trying the 5.0.0-preview.11 if you may consider using the SDK.

**Comment by maisarissi** [comment]
@edoust the target is to GA before the end of the year :) We believe the version we have so far, it's robust and stable enough. We are validating some scenarios, but we should be good to go soon!
