### ISSUE TITLE
Extend ICollectionPage<T>with property NextPageRequest

### ISSUE THREAD

**Issue by habex-ch** [microsoftgraph/msgraph-sdk-dotnet-core#42]
Each CollectionPage class has a property NextPageRequest. It would be great if this property is added to the interface `ICollectionPage<T>`.
I think something like that would do the trick:
```
public interface ICollectionPage<T,TRequest> : IList<T>, ICollection<T>, IEnumerable<T>, IEnumerable where TRequest : 
{
    TRequest NextPageRequest { get; }
    IList<T> CurrentPage { get; }
    IDictionary<string, object> AdditionalData { get; set; }
}
```
Example usage:
```
public interface IGraphServiceUsersCollectionPage : ICollectionPage<User,IGraphServiceUsersCollectionRequest>, IList<User>, ICollection<User>, IEnumerable<User>, IEnumerable
{
    ...
    IGraphServiceUsersCollectionRequest NextPageRequest { get; }
    ...
}
```

This would it make much easier to make some generic classes to work with Microsoft Graph.

 
[AB#7200](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7200)

**Comment by darrelmiller** [comment]
I'm working on the docs now.  It has been something we have been trying to get to for a while.  Hopefully when we get our backlog out of the way, we will be more prompt at getting docs out.

**Comment by habex-ch** [comment]
That are great news :-)

**Comment by maisarissi** [comment]
The Graph docs site has already [Page through a collection](https://docs.microsoft.com/en-us/graph/sdks/paging?view=graph-rest-1.0&tabs=csharp) for quite some time.

Closing this.
