### ISSUE TITLE
Public folder quirky

### ISSUE THREAD

**Issue by scpc0609** [microsoftgraph/msgraph-sdk-dotnet-core#43]
For Drives that have the "Public" folder, when you do Children query in the root, the DriveItem returned for "Public" has both File and Folder facets as null.

Also, Children query for Public folder does not return any child items, though it actually has Children.

**Comment by darrelmiller** [comment]
Can you confirm if you are seeing the same responses in Graph Explorer?  This helps us to identify if the problem is related to the service or to the SDKs.

**Comment by scpc0609** [comment]
Same response in Graph explorer. The remote facet has a folder item in both Graph explorer and SDK, but children query using the remote facet Id fails as well.

**Comment by ddyett** [comment]
service issue we can't address here.
