### ISSUE TITLE
Load/Expand Attachments without load contentBytes

### ISSUE THREAD

**Issue by mrfloppy82** [microsoftgraph/msgraph-sdk-dotnet-core#437]
Hello,

is there a way to load/expand the attachments collection without getting the content bytes? When the message has larger attchments, this is not optimal.

Regards

Nico

**Comment by andrueastman** [comment]
Hey @mrfloppy82,

Thanks for raising this.

It should be possible to add a nested `$select` statement in the `$expand` clause to choose only the properties of the navigation property that you wish.

In your case, the following query will only select the `id` ,`name` and `contentType` for the attachements

```http
https://graph.microsoft.com/v1.0/me/messages?$expand=attachments($select=id,name,contentType)
```

Using the SDK, this would look as below.

```cs
var messages = await graphClient.Me.Messages
	.Request()
	.Expand("attachments($select=id,name,contentType)")
	.GetAsync();
```

**Comment by mrfloppy82** [comment]
Hi @[andrueastman](https://github.com/andrueastman)

thanks, that works perfectly.

regards

Nico
