### ISSUE TITLE
Sometimes Receiving Bad-Request error while adding item to SharePoint list

### ISSUE THREAD

**Issue by basemvb** [microsoftgraph/msgraph-sdk-dotnet-core#454]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior.

**Comment by basemvb** [comment]
I'm using Microsoft.Graph.GraphServiceClient with .Net Core to add items to SharePoint List, it is working fine most of the times but sometimes it retrieves a BadRequest error and the same call working fine from deferent server.

I have tow deployment for the same app, one in Azure App service and it is working fine all the times without any issues, and other one in IIS in Azure VM and it is working fine but some times retrieves a BadRequest error.

The main issue that there is no details in the error to help me to understand what's happened in the request.

Appreciate your help and support.

**Code:**

Microsoft.Graph.GraphServiceClient graphClient = new Microsoft.Graph.GraphServiceClient(Models.GraphModel.createAzureClient());
                var listItem = new Microsoft.Graph.ListItem
                {
                    Fields = new Microsoft.Graph.FieldValueSet
                    {
                        AdditionalData = new Dictionary<string, object>()
                        {
                                {"Title", Subject},
                                {"upn", ToEmail},
                                {"content", Content},
                                {"URL", URL},
                                {"emailContent", EmailContent }
                        }
                    }
                };

 await graphClient.Sites[SiteID].Lists[ListID].Items
                    .Request()
                    .AddAsync(listItem);


**Error**: Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: Invalid request
Inner error:
	AdditionalData:
	date: 2022-06-26T13:38:11
	request-id: 84edf4c9-9bf9-4321-aa23-733f3c042fe4
	client-request-id: 84edf4c9-9bf9-4321-aa23-733f3c042fe4
ClientRequestId: 84edf4c9-9bf9-4321-aa23-733f3c042fe4

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at learningApplication.Web.Notifications.SharePointRepository.AddTeamsNotificationRecordWithGraph(String ToEmail, String Subject, String Content, String URL, String EmailContent)

Thanks in advance!

**Comment by andrueastman** [comment]
Hey @basemvb,

We've received feedback on this from the SharePoint API team and it seems that for this particular request id, one of the field items exceeds the maximum allowed number of characters allowed for the text field and that's why you get back the HTTP 400 status response.
