### ISSUE TITLE
Loading related skills,  responsibilities and pastProjects

### ISSUE THREAD

**Issue by PatriceSc** [microsoftgraph/msgraph-sdk-dotnet-core#456]
Hi,
Trying to load as well skills, responsibilities and pastProjects for users in my department but it fails so far either not loading silently or showing an "expression id in (guid1, guid2 etc..) is invalid" error message. "Select" is not supposed to work with string[] or do I miss something?
For now I have to enumerate users and load explicitely those related properties for each and every user.

**Comment by andrueastman** [comment]
Thanks for raising this @PatriceSc 

Any chance you can share any more information on the SDK version you are using as well as the sample code that leads to this error?

**Comment by PatriceSc** [comment]
For now with .NET 6 and Microsoft.Graph 4.33 I'm trying :`
const string tenantId = "***";
const string clientId = "***";
const string clientSecret = "***";
var credential= new Azure.Identity.ClientSecretCredential(tenantId, clientId, clientSecret);
var client = new Microsoft.Graph.GraphServiceClient(credential);
var response= await client.Users.Request()
       .Filter("(startswith(mail,'***') or startswith(mail,'****')) and startswith(department,'***')")
       .Select("*,skills").GetAsync();
foreach(var user in response)
{
    Console.WriteLine(user.Skills == null); // true for all users while 2 have skills
}
`
if using .Select("id,skills") I have a messsage such as expression id in (<guid1>,<guid2>,<guid3>) is not valid".

For now inside the loop I'm building calls to explicitely load skills for each user.

**Comment by andrueastman** [comment]
Any chance you are able to replicate this error when you test this out using the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)?

**Comment by PatriceSc** [comment]
Good point. I tried and realized it works or not depending on using "me" or "users". Giving a closer look in this direction this is actually documented at https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http :

**Comment by PatriceSc** [comment]
So it seems it could be just closed as "by design".
