### ISSUE TITLE
Change overload AddBatchRequestStep(BatchRequestStep batchRequestStep) return type to void

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet-core#49]
The current implementation of the `AddBatchRequestStep(BatchRequestStep batchRequestStep)` returns a boolean based on whether adding the batchRequestStep is successful or not.

We want to change the function and then throw the relevant ClientException when the addition is not successful.

Since this is already in use with existing customers the change should be ideally made the next time the SDK is updated with breaking changes.

### Other Links
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/47

**Comment by MIchaelMainer** [comment]
We changed this to return the id of the added batch step.
