### ISSUE TITLE
Call thread doesn't end from version 2.0.8 when using .net framework 4.6.2

### ISSUE THREAD

**Issue by MetaFactoK** [microsoftgraph/msgraph-sdk-dotnet-core#503]
I encounter an issue starting from version 2.0.8. My call to graph does not compute, and thread never ends.
Code to reproduce : [https://github.com/MetaFactoK/MF/blob/main/testGrapthApi.cs](https://github.com/MetaFactoK/MF/blob/main/testGrapthApi.cs)
I suspect this is linked to #363 

### Expected behavior

I should get informations concerning the user in my variable `user`

### Actual behavior

``` cs
await graphClient.Users[[MY_MAILBOX]].Request().GetAsync();
``` 
keep hanging, and I can't get its result

### Steps to reproduce the behavior

- Visual Studio 2019
- .net framework 4.6.2
- Microsoft.Graph.Beta 4.18.0

Working :
- Microsoft.Graph.Core 2.0.7

Not Working :
- Microsoft.Graph.Core 2.0.8

**Comment by andrueastman** [comment]
Hey @MetaFactoK,

Thanks for raising this. 

> https://github.com/MetaFactoK/MF/blob/main/testGrapthApi.cs

It seems the link to the repro project is broken, any chance you can update the link to help us investigate?

**Comment by andrueastman** [comment]
Hey @MetaFactoK,

Any chance you can add the csproj file for the project as well to get the full repro environment? Also, is there any reason that [the function](https://github.com/MetaFactoK/MF/blob/745fbf29a419fc1345e1021ae77b27024c93c994/testGrapthApi.cs#L1) is of the `async void` type?

**Comment by MetaFactoK** [comment]
Hello @andrueastman,

By digging more into the problem, the cause seems to be #364 instead.
We get the following error : "only http/1.0 and http/1.1 version requests are currently supported" and our code works with lastest version if we recompile while removing the code change
Note : This is not a proxy problem as we tried to work around it 

csproj file : https://github.com/MetaFactoK/MF/blob/main/TestGraphExch365.csproj
No particular reason for the function being async, but it doesn't work better while being synchronous

**Comment by andrueastman** [comment]
Thanks for the extra info @MetaFactoK 

Any chance you could share the entire sample project with all the files so that we can try to replicate? 
I've tried replicating the project with the same dependencies/configs from the csproj but the request executes successfully.

**Comment by MetaFactoK** [comment]
Hello @andrueastman 

You can find a project example here : https://github.com/MetaFactoK/MF/tree/main/TestExchange-UpToDate-NotWorking (only thing missing are credentials)

Update also concerning my last message, the problem with HTTP2 was actually due to something on our side. We resolved it, but we are back to square one with call pending and no significant error message

**Comment by andrueastman** [comment]
Hey @MetaFactoK,

I'm able to fetch the mailbox without issue using the sample provided. 

Any chance you are able to step in to the code and verify where the issue is caused on your side after making changes proposed in https://github.com/MetaFactoK/MF/pull/1
