### ISSUE TITLE
MAUI Android System.TypeLoadException

### ISSUE THREAD

**Issue by david-maw** [microsoftgraph/msgraph-sdk-dotnet-core#515]
### Expected behavior

Using a MAUI test program, I expected to see the same behavior on Android as Windows, the test program below simply logs in the user then displays the user's name. It works as expected on Windows.

### Actual behavior

On Android it throws an exception from
`graphClient.Me.Request().GetAsync();`
the exception message is "System.TypeLoadException: Could not resolve type with token 01000023 from typeref"

According to comments on Issue #413 this is resolved by pull #486 which is available in the preview package, Unfortunately was not able to verify this  because I didn't have much success switching to the preview package, the sample failed to build using it, I was able to detour some of the problems by adding a using for Microsft.Graph.Models but not all - are there migration hints anywhere, or is this just a temporary situation?
 
### Steps to reproduce the behavior

Clone https://github.com/david-maw/BugGraph.git thrn open up the project in Visual Studio and run it in Windows. Click the button labelled "Load User Info" and you'll be asked to log in to the "Xamarin Graph Tutorial" (I took the Client ID from a published sample). Once logged in the "Hello World!" will be replaced by "Hello <user's name>on Windows or an error message on Android. Check the VS output window the see details of the exception that prompted the error message.

**Comment by andrueastman** [comment]
Hey @david-maw,

As you pointed out, MAUI works with the preview of the SDK and not the older version. There are few breaking changes that come with the version and the upgrade guide for the same can be found at the link below. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md

I also tested out your sample app and made some changes to align with preview version to validate it worked at https://github.com/david-maw/BugGraph/pull/1. Let me know if it works out for you as well.

**Comment by david-maw** [comment]
It worked for me too, thanks @andrueastman , now I must go back to the original code and make that work in this SDK. in particular I need to deal with silent logon, cached credentials in Windows and paged responses - all of which seem like they have changed. Worse, my application reads a bunch of OneDrive files and using this interface adding `var drive = await graphClient.Me.Drive.GetAsync();` throws an OData exceptions because "Tenant does not have a SPO license." so I appreciate the help and the pointer to the upgrade guide, but while this may be a step forward I don't know if it solves my actual problem.

**Comment by andrueastman** [comment]
Thanks for the feedback @david-maw 

>  in particular I need to deal with silent logon, cached credentials in Windows and paged responses - all of which seem like they have changed

Any chance you could share some insights on your current implementation? I believe if one was using the `DelegateAuthenticationProvider`, you would mainly need to just move the code to the TokenProvider over as described [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#authentication).

> Worse, my application reads a bunch of OneDrive files and using this interface adding var drive = await graphClient.Me.Drive.GetAsync(); throws an OData exceptions because "Tenant does not have a SPO license."

I believe this isn't an issue with code but with the tenant not having a valid licence for OneDrive.

**Comment by david-maw** [comment]
Thanks for your help @andrueastman, I'm operating on the bleeding edge of comprehension here - between MAUI, MSAL, Android and the Graph SDK there are a lot of moving parts. My "license" problem is that my existing code allows me to open files in OneDrive but the new code doesn't however I think I figured out that the answer is that since all I care about is personal credentials I can use a different authority - https://login.microsoftonline.com/consumers/ instead of https://login.microsoftonline.com/{TenantId}/, with that in place, the tenant becomes irrelevant. That was my blocking issue, with it resolved I expect you are correct about the rest, I just have not done the research yet. FYI I extracted the relevant code into a GitHub repo at https://github.com/david-maw/MauiGraph-repro.git.

**Comment by david-maw** [comment]
@andrueastman, resolving the authority vs OneDrive access thing turned out to be even simpler than I thought. If I don't specify an authority at all, the default (https://login.microsoftonline.com/common/) seems to work fine for consumer credentials and access to OneDrive, which is just what I wanted.

As you suggested, just moving the cache code over was simple enough (I included what I ended up with at the end of this message). My next sticking point is that while 
```
await graphClient.Me.Drive.GetAsync();
```
seemed to work as expected, I could not persuade:
```
await graphClient.Me.Drive.Items,GetAsync();
```
to compile, am I missing something?

Here's the TokenProvider Code:, FYI

```
    public class TokenProvider : IAccessTokenProvider
    {

        // Using Microsoft.Identity.Client
        private readonly IPublicClientApplication publicClientApplication;

        public TokenProvider()
        {
            publicClientApplication = PublicClientApplicationBuilder.Create(AppConstants.ClientId)
                //.WithAuthority($"https://login.microsoftonline.com/consumers/") // Personal credentials only
                .WithDefaultRedirectUri()
                .Build();
        }

        private bool once = true;
        public async Task<string> GetAuthorizationTokenAsync(Uri uri, Dictionary<string, object> additionalAuthenticationContext = default, CancellationToken cancellationToken = default)
        {
            if (once)
            {
                once = false;
#if WINDOWS
                var storageProperties =
                     new StorageCreationPropertiesBuilder(@"TokenCache", @"C:\Temp")
                     .Build();

                // This hooks up the cross-platform cache into MSAL
                var cacheHelper = await MsalCacheHelper.CreateAsync(storageProperties);
                cacheHelper.RegisterCache(publicClientApplication.UserTokenCache);
#endif
            }
            try
            {
                var accounts = await publicClientApplication.GetAccountsAsync();
                var authenticationResult = await publicClientApplication.AcquireTokenSilent(AppConstants.Scopes, accounts.FirstOrDefault()).ExecuteAsync();

                // get the token and return it in your own way
                return authenticationResult.AccessToken;
            }
            catch (MsalUiRequiredException ex)
            {
                var authenticationResult = await publicClientApplication.AcquireTokenInteractive(AppConstants.Scopes)
#if ANDROID
                            .WithParentActivityOrWindow(Platform.CurrentActivity)
#endif
                            .ExecuteAsync();

                // get the token and return it in your own way
                return authenticationResult.AccessToken;
            }
        }
```

**Comment by andrueastman** [comment]
Hey @david-maw,

Due to the exploding number of paths created on expanding `\drive` path the metadata, some of the paths have been limited from being generated hence the lacking path that you observe.

To resolve this, you can get the driveId and use it on the Drives path to make the call as below.

```cs
var myDrive = await graphClient.Me.Drive.GetAsync();
var items = await graphClient.Drives[myDrive.Id].Root.Children.GetAsync();
```

**Comment by david-maw** [comment]
Thanks @andrueastman, that worked fine, if it's a permanent change then it's probably worth a mention in the upgrade guide. Next step is to take a shot at migrating the MauiGraph-repro project - I'll push the update once I have one.

**Comment by andrueastman** [comment]
> if it's a permanent change then it's probably worth a mention in the upgrade guide.

True. I'll make an update related to this. 

If it's okay we can close this issue and then you can re-open in the event any other issues arise?

**Comment by david-maw** [comment]
By all means close the event as resolved; it'll take me a while to integrate all the changes back into my original code and I'm happy to report another issue if something comes up along the way. Alternatively, I could reopen this one; do you have a preference?

Either way, thanks very much for your help, I might have been able to succeed without it, but the result would have been ugly at best!

**Comment by david-maw** [comment]
Well, that didn't take long! Now  I'm wrestling with:
```
await GraphClient.Me.Drive.Items[folderId].ItemWithPath(filename).Content.GetAsync();
```
The problem being how to migrate `ItemWithPath`, the simple replacement of `Me.Drive` with `Drives[myDriveId]` didn't seem to do the trick this time.

**Comment by andrueastman** [comment]
Closing this to follow up via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/538

**Comment by mfeingol** [comment]
@andrueastman: for those of us still on 4.5.x, is there any chance you could backport the fix from 5.0 for this issue? Porting to 5.0 is a significant task. Thanks.

**Comment by maisarissi** [comment]
Hi @mfeingol . Thank you very much for your comment.
We are no longer adding new functionalities/fixing bugs in v4.x. Backporting the fix is not only to cherry-pick commits, as v5 has a completely distinct set of dependencies, including a new code generator, Kiota.
Unfortunately, we won't support MAUI in older versions.

**Comment by mfeingol** [comment]
Fair enough. Thanks for your reply.
