### ISSUE TITLE
New method to insert client-request-id

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/msgraph-sdk-dotnet-core#52]
Currently in 1.18.0 we can add a client-request-id to a request using

```
var headerOptions = new List<HeaderOption>()
{
       new HeaderOption("client-request-id", "dddddddd-dddd-dddd-dddd-dddddddddddd")
};
return await graphClient.Me.Request(headerOptions).GetAsync();
```

Could this be a possibility to mirror how we handle Select, OrderBy etc.?

```
return await graphClient.Me.Request()
   .ClientRequestId("dddddddd-dddd-dddd-dddd-dddddddddddd")
   .GetAsync();
```

**Comment by darrelmiller** [comment]
If you don't provide a `client-request-id` header then one will be inserted automatically.  You can access that value if you need it.  What is the scenario where someone would want to set it explicitly?

**Comment by ddyett** [comment]
closing this one as i don't think there's a strong reason here to change the pattern.
