### ISSUE TITLE
LargeFileUploadTask with a zero length stream throws TaskCanceledException "Upload failed too many times"

### ISSUE THREAD

**Issue by redback790** [microsoftgraph/msgraph-sdk-dotnet-core#554]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

Using an instance of LargeFileUploadTask.cs with zero length Stream should either create a zero-sized file or throw ArgumentException.

For a small sized stream, e.g. 4 bytes, it works fine and a new small file is created at the requested SharePoint path.

### Actual behavior

There is an unhelpful exception thrown: 
```
Unhandled exception. System.Threading.Tasks.TaskCanceledException: Upload failed too many times. See InnerException for list of exceptions that occured.
 ---> System.AggregateException: One or more errors occurred.
   --- End of inner exception stack trace ---
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
```

### Steps to reproduce the behavior

Microsoft.Graph 4.47.0

Example code below:
```
string localFilePath = Path.Join(Path.GetTempPath(), "testzerosizedfile.tmp");
using (File.Create(localFilePath, 0, FileOptions.None)) {} // create zero-sized file
using FileStream fileStream = new FileStream(localFilePath, FileMode.Open);
IDriveItemRequestBuilder requestBuilder = graphClient.Drives[driveId].Root.ItemWithPath("testzerosizedfile.tmp");
UploadSession uploadSession = await requestBuilder.CreateUploadSession().Request().PostAsync();
LargeFileUploadTask<DriveItem> fileUploadTask = new LargeFileUploadTask<DriveItem>(uploadSession, content, maxSliceSize);
UploadResult<DriveItem> uploadResult = await fileUploadTask.UploadAsync();
```

**Comment by a-bondarchuk-kdd** [comment]
@redback790 I've had the same issue a few days ago. `Upload failed too many times. See InnerException for list of exceptions that occured.` exception is not helpful. It would be very nice if it's possible to detect an empty byte array and throw ArgumentException
