### ISSUE TITLE
RequestBuilder should not add QueryParameters in the final URI if they are null or empty

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/msgraph-sdk-dotnet-core#564]
issue #196 is representing in the Kiota-generated SDK.

Executing this:
`var users = await _graphClient.Users.GetAsync(rc => rc.QueryParameters.Search = "")`

will result in an error.

**Comment by andrueastman** [comment]
Thanks for this @Licantrop0 

This should be investigated and solved via https://github.com/microsoft/kiota-abstractions-dotnet/issues/60 so we'll close this and track it from there.
