### ISSUE TITLE
Update RuntimeFrameworkVersion for Unit Test Project

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/msgraph-sdk-dotnet-core#60]
It'd be great to use a newer supported version of .NET Core to run the tests and update the `RuntimeFrameworkVersion` in the project file for the baseline.  The version specified 1.0.4 doesn't even have an installer, it's just a zip file with no instructions.

### Expected behavior
Able to run tests easily out of VS 2019.

### Actual behavior
Can't run tests without using v1.04 of .NET Core which is end-of-life and doesn't have an installer.

### Steps to reproduce the behavior
Clone repo
Try and run tests

 
[AB#6306](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6306)

**Comment by andrueastman** [comment]
Closing this as we have already updated the runtime of the unit test project to net core 3.1. See [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/015f3761f2357ebd439936e6c278d350fc8646ec/tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj#L3)
