### ISSUE TITLE
PageIterator doesn't give the delta link after completing the iteration

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-dotnet-core#619]
`PageIterator` does not return the `@odata.nextLink` property, making it unusable for delta queries.

### Expected behavior

If you use the `PageIterator` class to iterate through a delta response, the `Deltalink` property should contain the value of the `@odata.deltaLink` property returned by the API. This value should be usable to create a new `DeltaRequestBuilder`.

### Actual behavior

The `Deltalink` property is empty (`""`). The value is there in the iterator's private `_currentPage.OdataDeltaLink` property:

![image](https://user-images.githubusercontent.com/8966342/224073521-65c65922-be7d-4cee-8227-fe2bcedeff57.png)

### Steps to reproduce the behavior

`Microsoft.Graph` version 5.1.0

```csharp
// Local list of mail folders
var localMailFolders = new List<MailFolder>();

try
{
    // Get the first page of folders
    var mailFoldersDelta = await graphClient.Me
        .MailFolders
        .Delta
        .GetAsync();

    while (mailFoldersDelta != null)
    {
        var iterator = PageIterator<MailFolder, DeltaResponse>
            .CreatePageIterator(graphClient, mailFoldersDelta, async folder =>
            {
                localMailFolders.Add(folder);
                return true;
            });

        await iterator.IterateAsync();

        Console.WriteLine($"Sync complete. Delta link: {iterator.Deltalink}");
        Console.WriteLine($"Waiting for {pollInterval} seconds...");
        await Task.Delay(pollInterval * 1000);

        // Following line throws ArgumentNullException
        var deltaRequest = new DeltaRequestBuilder(iterator.Deltalink, graphClient.RequestAdapter);
        mailFoldersDelta = await deltaRequest.GetAsync();
    }
}
catch (Exception ex)
{
    Console.WriteLine($"Error: {ex.Message}");
    if (ex is ODataError odataErr)
    {
        Console.WriteLine(odataErr.Message);
    }
}
```

**Comment by vijmax** [comment]
Is this patch provided for GoSDK as well ? 
I see after finishing iterating via pageiterator deltaLink is not available still. We have to manually do nextPageUrl = delta.GetOdataNextLink() twice (till GetOdataNextLink() returns null) before we can get the deltalink.

**Comment by andrueastman** [comment]
Hey @vijmax,

Any chance you can create an issue for the Go sdk with the repro scenarios at https://github.com/microsoftgraph/msgraph-sdk-go-core/issues so that this may be followed up?
