### ISSUE TITLE
BatchResponseContent and BatchResponseContentCollection should have validate success

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/msgraph-sdk-dotnet-core#621]
Batching should make your application a lot faster, but the SDK has no way to check if all modifications are successful without checking each individual request.

I'm also the creator of #613 so I know a thing or two on batching. This new proposal needs addition input, because I'm not sure on the solution either.

Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

If you added 15 items to a batch and it's executed I would expect there to be a way to check if all individual requests have a success response code (`200`, `202` or `204`).

Something like:

```csharp
var batchCollection = new BatchRequestContentCollection(graphClient);
foreach (var task in tasks)
{
    await batchCollection.AddBatchRequestStepAsync(graphClient.Me.Todo.Lists[listId].Tasks.ToPostRequestInformation(task));
}
var result = await graphClient.Batch.PostAsync(batchCollection);
var success = await result.ValidateSuccess();
```

And maybe even return the failed requests somehow for retry.

### Actual behavior

`var success = await result.ValidateSuccess();` is not available.

### Steps to reproduce the behavior

Run [this program](https://github.com/svrooij/msgraph-sdk-dotnet-batching/tree/main/sample/BatchClient) and see the batch execute successfully, while individual requests not all succeed (16 of the 20 requests are blocked with a `429` error code).

**Comment by andrueastman** [comment]
Thanks for raising this @svrooij,

To understand the issue better, would this be the equivalent of doing the following?

```cs
            var responses = await result.GetResponsesAsync();
            var allReponsesSuccessFull = responses.Any( response => !response.Value.IsSuccessStatusCode);//all the responses are successfull?

            var failedResponses = responses.Where(response => !response.Value.IsSuccessStatusCode);//the responses which do not have a success code.
```

**Comment by svrooij** [comment]
I was worried on the message in the xml docs `all httpresponsemessage objects need to be disposed`

And this seems correct for the first part, the second part is to have it return the **requests that failed** not the responses. So for a batch where 16 out of 20 requests fail (batching Todo tasks only accepts 4 apparently) I would want to get all the 16 requests that failed to do a retry.

Maybe the Batch limit for the BatchRequestContentCollection should be configurable with a default of 20. So I could still use the batching functionally even though it's not as efficient as I wanted.
