### ISSUE TITLE
v5 PageIterator is broken

### ISSUE THREAD

**Issue by NetworkGithub** [microsoftgraph/msgraph-sdk-dotnet-core#625]
I have a bug the same as:
[#1676 msgraph-sdk-dotnet](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1676)

Describe the bug
There are two extensions

`public static PageIterator<TEntity, TCollectionPage> CreatePageIterator(IBaseClient client, TCollectionPage page, Func<TEntity, bool> callback, Func<RequestInformation, RequestInformation> requestConfigurator = null)`

`public static PageIterator<TEntity, TCollectionPage> CreatePageIterator(IBaseClient client, TCollectionPage page, Func<TEntity, Task<bool>> asyncCallback, Func<RequestInformation, RequestInformation> requestConfigurator = null)`

When I use the first variant in code

`var pageIterator = PageIterator<Message, MessageCollectionResponse>.CreatePageIterator(_client, messagesResponse, (message) =>
                {
                    ...
                    return true;
                });`
I get compile error

error CS0029: Cannot implicitly convert type 'bool' to 'System.Threading.Tasks.Task<bool>'
error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type
When I use the second variant

`var pageIterator = PageIterator<Message, MessageCollectionResponse>.CreatePageIterator(_client, messagesResponse, async (message) =>
                {
                    await Task.CompletedTask;
                    return true;
                });`

I get another compile error

error CS4010: Cannot convert async lambda expression to delegate type 'Func<Message, bool>'. An async lambda expression may return void, Task or Task<T>, none of which are convertible to 'Func<Message, bool>'

As a result I'm not able to use PageIterator

To Reproduce
`use public static PageIterator<TEntity, TCollectionPage> CreatePageIterator(IBaseClient client, TCollectionPage page, Func<TEntity, bool> callback, Func<RequestInformation, RequestInformation> requestConfigurator = null)`

Expected behavior
No compile error

Screenshots
![image](https://user-images.githubusercontent.com/55289766/225064325-a9cdb1cb-9828-4ab9-b344-b3dd4f9fb60a.png)

Client version
5.1.0

Desktop (please complete the following information):

OS: Windows 11
.NET: 7.0

**Comment by andrueastman** [comment]
Thanks for raising this @NetworkGithub 

Any chance you are able to clean and rebuild the solution as done in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1676

Also, any chance you can reproduce with the latest version 5.1.0?

**Comment by NetworkGithub** [comment]
Sorry I put the wrong client version in the report.
Already using 5.1.0 and cleaning / rebuilding has no effect.

**Comment by andrueastman** [comment]
Thanks for confirming. 
Any chance you can share a repro project to help us understand the issue better and investigate?

**Comment by NetworkGithub** [comment]
[Bug 625 Repro](https://github.com/NetworkGithub/Bug625Repro)

**Comment by andrueastman** [comment]
Looks like the second parameter was passed incorrectly. 
https://github.com/NetworkGithub/Bug625Repro/pull/1/files should resolve this.

**Comment by NetworkGithub** [comment]
Oh, yes, that has sorted it, thank you.
