### ISSUE TITLE
Too much TargetFrameworks, and HttpClientResponsibility

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/msgraph-sdk-dotnet-core#640]
This is not so much an issue, more a design decision.

Currently the TargetFrameworks are really big, like `<TargetFrameworks>netstandard2.0;net462;net6.0;net6.0-android;net6.0-ios;net6.0-maccatalyst;net6.0-macos;net6.0-windows</TargetFrameworks>`

To my understanding this is purely so it can create an efficient `HttpClient` for each platform. That seems to be the only reason why it's configured like this. So my question is:

Why is it this library' responsibility to create an efficient HttpClient? And shouldn't you guys just stimulate the use of [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http) for generating the most efficient httpclienthandler and keeping track of it so it does not run out of available sockets.

Reasons I ask:

- Current implementation fails in Blazor Webassembly, (but is worked around with [this fix](https://github.com/svrooij/BlazorGraphExplorer/commit/ab989ff959883f43e7ead10ff4e3c506022dbf33#diff-6cac03a875cb22b9a87eb4fcefe4b07e2dd088322611b235c7edf60382133063R40-R43), by using Microsoft.Extensions.Http anyways)
- Having such a big `TargetFrameworks`, makes contributing immensely difficult, since you would need to have all those frameworks installed to be able to contribute, else the project will not build and you get all those red lines in VS.

I would opt for a solution that accepts an `HttpClient` and sets the default with `new HttpClient()` if not specified, no trickery with for all the different platforms.

**Comment by DavidParks8** [comment]
To further iterate the http issue, because this library doesn't make use of Microsoft.Extensions.Http, sockets are not managed according to best practices and the performance is subpar compared to IHttpClientFactory-backed http clients.

**Comment by adamedx** [comment]
@MIchaelMainer thoughts? We're starting to see challenges across multiple applications along these lines. It seems the proposal in this issue could address the concern without a breaking change. Should we just submit a PR?

**Comment by svrooij** [comment]
@adamedx while my proposed solution is not a breaking change, it still is a big change. Because the current solution tries do do some efficiently steps. All those would be removed if you remove all the extra targeted frameworks.

I would still like to have the development team consider this.

1. Enabling easier contributions
2. Not managing getting an efficient HttpClient in every other library, and delegating that responsibility to a single package (and/or the developer).
3. Less magic behind the scenes
4. Way faster build times
5. Way smaller package on nuget because of less target frameworks

**Comment by MIchaelMainer** [comment]
Partially related to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/510. If I understand correctly, IHttpClientFactory handles getting the appropriate client as it does the conditional checks itself for the target frameworks so that in this library, we wouldn't need the `#if` preprocessor directives to get the correctly configured HttpClient for the target framework.  

https://github.com/microsoft/kiota-http-dotnet would need to implement [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http).

I defer to @andrueastman who owns this project on how to move forward.

**Comment by adamedx** [comment]
This seems to be blocking adoption @MIchaelMainer  and may also be a COGS issue. Is there a way we can prioritize a decision on this in some time frame so we can get people out of a holding pattern? We really don't want people rolling their own libraries!

**Comment by andrueastman** [comment]
Closing this for now. 

Using HttpClientFactory with Kiota based clients is documented at https://learn.microsoft.com/en-us/openapi/kiota/tutorials/dotnet-dependency-injection and `TargetFrameworks` are no longer mandatory to be installed to run the project.

**Comment by svrooij** [comment]
@andrueastman Thanks for the update (and referring to new docs written by me), I like the [solution](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/67164293c2f5dcdf31a6cb64aa33539996a2c450/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L34) with the maui targets.

This raises another question though. Since you seen to target `netstandard2.0` and `net462`, will this package (and by that the Graph SDK itself) profit from any of the `net6.0` and `net8.0` improvements that are in the Kiota package?

- Kiota targets `netstandard2.0;netstandard2.1;net5.0;net6.0;net8.0` (I know that would be the next thing to conquer). 
- This library `Microsoft.Graph.Core` targets `netstandard2.0;net462;$(MauiTargets)`

So my guess is that if you use the graph sdk in a `net6.0` or `net8.0` project you'll be getting the `netstandard2.0` version of the Kiota packages? Including all the for `netstandard2.0` mandatory packages like `Microsoft.Bcl.AsyncInterfaces`.
