### ISSUE TITLE
Timeout property on passed in HttpClient is modified

### ISSUE THREAD

**Issue by fowl2** [microsoftgraph/msgraph-sdk-dotnet-core#67]
The `Timeout` property of any `HttpClient` passed into `GraphServiceClient` is [set](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/7bf1f20f3772aa0e3f01f9022901d7e0367a7feb/src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs#L49) by the [constructor](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/7bf1f20f3772aa0e3f01f9022901d7e0367a7feb/src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs#L30). 

This is bad because:
1. I could be using the `HttpClient` for something else.
1. If `HttpClient` had already been used it will throw an exception.

### Steps to reproduce the behavior

```
var httpClient = new HttpClient();
// make any request with the client
var graphServiceClient = new GraphServiceClient(httpClient); // exception!
```

### Expected behavour

The timeout should be implemented [per request](https://thomaslevesque.com/2018/02/25/better-timeout-handling-with-httpclient/).

### Actual behaviour

> Microsoft.Graph.ServiceException: 'Code: notAllowed
> Message: Overall timeout cannot be set after the first request is sent.
> InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.

related: #38

**Comment by darrelmiller** [comment]
Unfortunately we can't change the implementation of HttpClient.  However, if we pass HttpClient into the constructor we could avoid trying to set any properties that can't be changed once a request has been sent.
