### ISSUE TITLE
Graph SDK wraps exceptions and hides the raw exception from callers

### ISSUE THREAD

**Issue by adnivart** [microsoftgraph/msgraph-sdk-dotnet-core#700]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

The Graph SDK should throw back any raw exception to the caller without wrapping it unnecessarily.

### Actual behavior

Wrapping the exception hides the context of the real problem from the caller inside the inner exception(s). The SDK should just use `throw` to give back the real error to the caller.

Here is another public example of what callers have to handle: [How to solve “Microsoft.graph.serviceexception code "generalException" an error occurred sending the request” while fetching calendar events?](https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth/issues/96).

### Steps to reproduce the behavior

1. I am using Microsoft.Graph 4.50.0 and Microsoft.Graph.Core 2.0.15
1. The code in question is in the [SimpleHttpProvider.cs](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/98f853c180c5c312afb0ec8548acbe36b408d9f2/src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs):
   ```cs
   throw new ServiceException(
   new Error
   {
       Code = ErrorConstants.Codes.GeneralException,
       Message = ErrorConstants.Messages.UnexpectedExceptionOnSend,
   },
   exception);
   ```
1. Use the Graph SDK and try to make a request when the host is unable to send the request (say there are connection issues or it runs into SNAT port exhaustion.
1. Result:
   * Expected: the caller gets an exception related to the root issue (connection error, etc.)
   * Actual: the caller received a "generalException" error

**Comment by andrueastman** [comment]
Thanks for raising this @adnivart 

The latest version of the graph sdk (Microsoft.Graph 5.x.x and Microsoft.Graph.Core 3.x.x) now work with the Kiota abstractions that do not follow this general pattern and Service errors are as defined in the metadata through the ApiException/ODataError class. As the [SimpleHttpProvider.cs](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/98f853c180c5c312afb0ec8548acbe36b408d9f2/src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs) is now deprecated, it would be unlikely that we would be making this change.

**Comment by adnivart** [comment]
Thanks for sharing @andrueastman. Is it reasonable to assume that because of the new Kiota abstractions, this problem doesn't exist on the latest Graph SDK?

Also, you mentioned that SimpleHttpProvider.cs is deprecated. Does that also mean the package versions I listed above are also considered deprecated? If they are not deprecated (I didn't see this noted anywhere), I would argue that patching those major versions of the packages would be valuable.

**Comment by andrueastman** [comment]
> this problem doesn't exist on the latest Graph SDK?

This is correct. Newer versions do not use the types and all the transport specific concepts in the library have been abstracted to the kiota library and updates will be made only on the latest version.s
