### ISSUE TITLE
Unable to Load one or more of the requested types could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph, Version=5.24.0'

### ISSUE THREAD

**Issue by rajkumar200059** [microsoftgraph/msgraph-sdk-dotnet-core#714]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

**Comment by rajkumar200059** [comment]
After we updating the Library from 4.54.0 to 5.24.0 , when we Luanching the application we are seeing this error

**Comment by andrueastman** [comment]
Thanks for raising this @rajkumar200059 

Any chance you are able to share more details on the platform/OS runtime when this issue occurs? Does this error occur when making a specific API call? And what version of the SDK are you updating from?

**Comment by rajkumar200059** [comment]
it is on windows platform and it is occurring when it's launching the solution for debugging

**Comment by andrueastman** [comment]
Any chance you can confirm a place where the User type is referenced? One of the [breaking changes in V5 is the changing of namespaces](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#namespacesusings-changes) and thus `Microsoft.Graph.User` would actually need to be `Microsoft.Graph.Models.User`

**Comment by rajkumar200059** [comment]
I have not referenced user type anywhere

**Comment by andrueastman** [comment]
Any chance you can share a sample project that reproduces the issue to help us investigate? Or a copy of the csproj file? There maybe an incompatible dependency present as well?

**Comment by rajkumar200059** [comment]
Need your help in the sample code to read the Application users, Application Groups, User Groups information,  User Token and Application Token through Microsoft Graph Latest(5.24.0) version in .net core

**Comment by andrueastman** [comment]
@rajkumar200059 Please re-open if this still an issue on the latest sdk version.
