### ISSUE TITLE
Update Team - MS Graph SDK

### ISSUE THREAD

**Issue by Legfordrum** [microsoftgraph/msgraph-sdk-dotnet-core#75]
I have tried to update the Name of a team, no error is being returned, however the Team name is not updating.

Is this an error with the service?

Example Snippet Below

```
private static async void testUpdate(AzureADConnection azureADConnection, String TeamNameId)
        {
            Team originalTeam = AuthenticationHelper.graphClient(azureADConnection).Teams[TeamNameId].Request().GetAsync().Result;

            Team Update = new Team();
            Team Updated = new Team();

            Update.DisplayName = "New Team Name";

            Updated= await AuthenticationHelper.graphClient(azureADConnection).Teams[TeamNameId].Request().UpdateAsync(Update);
            string gh;
            gh = "ssss";
        }
``` 
[AB#7204](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7204)

**Comment by MIchaelMainer** [comment]
Thank you for asking this question. This is likely an issue with the service. Can you please provide us the sanitized http request and response so we can determine the source of this issue?

**Comment by MIchaelMainer** [comment]
Can you try updating the group name and let us know if that changes the team name?

**Comment by andrueastman** [comment]
Ping @Legfordrum

**Comment by andrueastman** [comment]
@Legfordrum Please feel free to reopen this issue. Closing this for now.
