### ISSUE TITLE
Migration from old release management to YAML deployments

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet-core#808]
To prepare for our migration to 1es templates, we need to first migrate off the old release management (JSON) to the newer YAML deployments for the following definitions:
- [msgraph-beta-sdk-dotnet.preview](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_release?_a=releases&view=all&definitionId=19)
- [msgraph-sdk-dotnet.production](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_release?_a=releases&view=all&definitionId=18)
- [msgraph-sdk-dotnet-core.preview](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_release?_a=releases&view=all&definitionId=16)
- [msgraph-sdk-dotnet-core.production](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_release?_a=releases&view=all&definitionId=17) (merge this one with the previous)

[here is an example of how it's done in kiota abstractions](https://github.com/microsoft/kiota-abstractions-dotnet/blob/e95b9a71919b3bed12ad0dd83789c948f7473e05/.azure-pipelines/ci-build.yml#L259)

once the migration is done, we should disable the older definitions

**Comment by andrueastman** [comment]
Closing this one for now as this is now resolved via 
Core - https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/810
V1 - https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2370
Beta - https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/810
