### ISSUE TITLE
list team members functionality to Microsoft Graph fluent api

### ISSUE THREAD

**Issue by kendrahavens** [microsoftgraph/msgraph-sdk-dotnet-core#82]
[Transferred from developer community](https://developercommunity.visualstudio.com/content/idea/854442/list-team-members-functionality-to-microsoft-graph.html)

> It's a curious thing that Microsoft Teams can have different members than the underlying AD Group, but there appears to be no way of getting Teams team members to a c# function to do some merging of the two...shouldn't there be a list members functionality to Teams team as is for AD group ???

> Any plans on implementing this anytime soon ?

**Comment by darrelmiller** [comment]
This repo for is for the core of the C# library and not related to any particular service, so it's not the right location for this question.  However, having read the docs for this item https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http  I don't understand why the group membership and the team membership would be different.  The docs say it is the same.

It would be good to get some clarification on why it is assumed they are different.

**Comment by MIchaelMainer** [comment]
Aww, I think I see. All members of a group are in the team. Teams can have guest users that are not in the group. This is a good docs issue.

**Comment by MIchaelMainer** [comment]
This API is not in the service API so it won't be found in the client. We don't have an ETA, you'll need to ask this of the Teams API team . The workaround for the moment is to get the group for that team, and then use that to get the members of the group.
