### ISSUE TITLE
Can't build correct request for deleting rows in excel table

### ISSUE THREAD

**Issue by CiesielskiB** [microsoftgraph/msgraph-sdk-dotnet-core#83]
Hi, I've been trying to use Graph sdk to call the Api but when i tried to build a request to delete a row from excel table there seems to be no way of doing so.

According to this documentation [https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-beta#delete-table-row]( https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-beta#delete-table-row ) Uri should look like this (https://graph.microsoft.com/v1.0/me/drive/items/{"workbookId"}/workbook/tables/{"TableId"}/rows/ItemAt(index={"index"}))  with Delete as method, but options given to me when building the request with graph sdk is to use Put, Patch or Get methods, there is no delete and I'm confiused if delete is possible to do when using the Sdks build in requests.

**Comment by MIchaelMainer** [comment]
@CiesielskiB, here's a workaround:

```csharp
var requestUrl = client.Users["userId"].Drive.Items["01KA5JMEA7GNMTADXTINDZ7OW7ROGFDU7N"].Workbook.Tables["Table1"].Rows.ItemAt(1).Request().RequestUrl;
	
HttpRequestMessage hrm = new HttpRequestMessage(HttpMethod.Delete, requestUrl);
	
await client.AuthenticationProvider.AuthenticateRequestAsync(hrm);

HttpResponseMessage response = await client.HttpProvider.SendAsync(hrm);
```

I believe this issue falls under needed composable function support. https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/233
If a function is composable, we may need to support all http methods in the generator.

**Comment by CiesielskiB** [comment]
Using simmilar method I managed to get it to work, thanks for the response.

**Comment by ddyett** [comment]
closing as tracked by https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/233
