### ISSUE TITLE
Resource not found for the segment 'riskDetections'.

### ISSUE THREAD

**Issue by cornerbowlsoftware** [microsoftgraph/msgraph-sdk-dotnet-core#838]
### Expected behavior
A call to GraphServiceClient.RiskDetections.GetAsync should return without errors.

### Actual behavior
The following exception is thrown: 
'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' 
Resource not found for the segment 'riskDetections'.

### Steps to reproduce the behavior
Install Microsoft.Graph.Core 3.0.7 and notice the call is successful and risky entries return.
Install Microsoft.Graph.Core 3.0.8 and notice the call is throws the exception.

The following sample code was executed from a .Net 8 application running on Windows 11.

```
var f = $"ActivityDateTime ge {startDT.ToUniversalTime():yyyy-MM-ddTHH:mm:ss.fffZ}";

List<RiskDetection>? auditLogRoot = null;
try
{
    var response = await graphClient.RiskDetections.GetAsync(rc =>
    {
        rc.QueryParameters.Filter = f;
        rc.QueryParameters.Orderby = new[] { "ActivityDateTime asc" };
    });
    ArgumentNullExceptionExtensions.ThrowIfNull(response);
    ArgumentNullExceptionExtensions.ThrowIfNull(response.Value);
    auditLogRoot = response.Value;
}
catch (ODataError ex)
{
}

```

**Comment by andrueastman** [comment]
Thanks for raising this @cornerbowlsoftware 

Just to confirm here, are you only changing the version of the core package, what about the beta package version?

Are you able to share the values in the of the url built in the two scenarios by using the sample below?

```cs
            var requestInfomation = graphClient.RiskDetections.ToGetRequestInformation(rc =>
            {
                rc.QueryParameters.Filter = f;
                rc.QueryParameters.Orderby = new[] { "ActivityDateTime asc" };
            });

            Console.WriteLine(requestInfomation.URI.OriginalString);
```

**Comment by cornerbowlsoftware** [comment]
@andrueastman All I do is switch between the versions.  There is not URL, I am using the C# Graph API as seen in the code snippet.

**Comment by andrueastman** [comment]
Could you try to get the generated url using the two version with the sample I shared above? I'd like to know whether different urls are built. Also, does the issue occur with the latest core package?

**Comment by cornerbowlsoftware** [comment]
v3.0.7:
https://graph.microsoft.com/beta/riskDetections?%24filter=ActivityDateTime%20ge%202024-05-18T20%3A49%3A22.086Z&%24orderby=ActivityDateTime%20asc

v3.0.8:
https://graph.microsoft.com/v1.0//riskDetections?%24filter=ActivityDateTime%20ge%202024-05-18T20%3A49%3A22.086Z&%24orderby=ActivityDateTime%20asc

Yep, look at that.  The Beta API isn't being called so the function is totally busted.

**Comment by cornerbowlsoftware** [comment]
Ok so I checked my project and I had both this library and the Microsoft.Graph.Beta packages installed. I'm not sure why both were installed.  I removed the 3.0.8 library and am instead using the Beta 5.25 pre release and it is working as expected.

**Comment by andrueastman** [comment]
Out of curiosity, is there a specific reason to not update the `Microsoft.Graph.Beta` pacakge? The latest version is [5.75.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/5.75.0-preview) which should pull in the latest version of the core library.

**Comment by cornerbowlsoftware** [comment]
Sorry I miss-typed.  That's the version I am using which is linking to the v3.0.5 library now out of date.

**Comment by cornerbowlsoftware** [comment]
@andrueastman You are correct I am using Microsoft.Graph.Beta 5.25.0-preview which is the latest according to NuGet.org.  If there is another version I certainly would like to update to that version.

**Comment by cornerbowlsoftware** [comment]
Ah yes I had turned preview off so it never showed the latest version.  I will try now.

**Comment by cornerbowlsoftware** [comment]
What's really strange is my project references .NetStandard Library 2.0.3 which explicitly states it is built against System.IO.FileSystem.Primitives 4.3.0, however when attempting to install 5.75. previewof this library I am presented with the error: 

`NU1605: Warning As Error: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. `
