### ISSUE TITLE
ErrorEntityNotFound - Exception of type 'Microsoft.Fast.Profile.Core.Exception.ImageNotFoundException' was thrown.

### ISSUE THREAD

**Issue by epardos1973** [microsoftgraph/msgraph-sdk-dotnet-core#851]
### Describe the bug

I have created an application in microsoft entra ID with the next permissions:

![permissions](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/assets/22658245/8f933e4d-3d9e-4780-a5bf-35fb2e50d066)

When I try to recover the any user´s photo profile I received

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/assets/22658245/85698ec5-b95e-4fe9-b3f2-10260f3538e5)

### Expected behavior

Expected behaviour is to show the image associated to use

### How to reproduce

You need create an microsoft entra application, give the necessary permissions and ask for any user´s photo profile

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @epardos1973 

As this is an API related question (and this repo is mainly intended for SDK related issues) the right place to ask the question would be at https://aka.ms/askGraph. 

The error seems to suggest that the specific user does not have a photo associated with it (404 http status code). Any chance you can confirm if the user has a photo?

**Comment by epardos1973** [comment]
Thanks for answer

![EntraM](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/assets/22658245/465a4b50-3c79-4b5f-9837-b5a4747dc19e)


All users in Microsoft Entra have profile photo, these photos have been set by the administrator. 

I forgot to say that I have this problem in a trial version, it does not occur in Microsoft Entra within the company. Could be this the reason?

Thanks in advance.

**Comment by andrueastman** [comment]
@epardos1973 I'm not sure if the trail status would have anything to do with it.

Any chance you can try uploading a new photo to the user and trying to request again?
I would then suggest asking a question with the API owners to get clarity on whether there are limitations with the trial accounts over at https://aka.ms/askGraph
