### ISSUE TITLE
Getting items from sharepoint list with read own items only enabled

### ISSUE THREAD

**Issue by CiesielskiB** [microsoftgraph/msgraph-sdk-dotnet-core#86]
Hi,
While working with a SharePoint list and the MS Graph API I stumbled upon a problem I have no idea how to fix. I’m not sure if it’s a bug or if there is another way around it.

I have a SharePoint list, with the option to read items only created by the user enabled, so users can’t see other users' information. I have an application account that is an owner of that list and has full control over it (also full control as in the permission level) and as this user I am able to read all the items added to the list.
Now I would like to use the MS Graph API to get items from the list in my application and it worked fine on a test list, with the "read items only created by the user" option disabled. When I used it on the list with that option enabled, I wasn’t getting any items and through investigation I found out that this very option causes the problem.
Is that the desired behavior? I feel like I should be able to read all the items just fine as the owner of that list with the "full control" permission. Am I missing something?
Any help would be appreciated.

**Comment by MIchaelMainer** [comment]
Thank you for reporting this issue. This appears to be a question about the SharePoint API. This repository is specific to the .Net client library. Questions about the service API or configuration should be posted to StackOverflow and tagged with microsoft-graph and sharepoint.
