### ISSUE TITLE
Branch naming alignment

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet-core#865]
- [ ] Delete all references to master in pipelines.
- [ ] Rename the master branch to main.

**Comment by baywet** [comment]
@andrueastman should we also create an issue to setup release please here after those changes are done?

**Comment by andrueastman** [comment]
I believe this issue will refactor changes made in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/856 and https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/869
