### ISSUE TITLE
Microsoft.Graph GetAsync(cancellationToken) API stuck indefinitely

### ISSUE THREAD

**Issue by z2alam** [microsoftgraph/msgraph-sdk-dotnet-core#90]
We have a service within Microsoft, and we use MsGraphSDK to sync incremental changes from AAD to our customer domain-controllers...

We have recently noticed a problematic issue, which happened only once so far in couple months...

What we noticed was the call to get next page got stuck indefinitely, and would never timeout...
It doesn't honor the cancellation either. This means that we can't stop our service in the machine. The only way to come out of this issue is to force kill the service...
The way how our service is designed, it's not easy to do these manual interventions to bring the sync out of this infinite loop...

Here's the call where it got stuck:

var nextUserPage = await nextUserPageReq.GetAsync(cancellationToken);

Again, we tried to cancel the cancellationToken to come out of this issue, but even that didn't work.

Here're some more info that might be helpful?

TimeStamp: 2020-01-30T04:54:08+00:00
SDK-Version: 1.18
SDK-Core-Version: 1.18
NextLink (beginning-only): https://graph.microsoft.com/v1.0/users/microsoft.graph.delta?$deltatoken=JHO-LXtOEomDYiJmLn8K_fdUgXvj_2FJcHtfa086IlZofJ-CaGp8N5sQBCdle-CUDHpHow_gQLxMORJGHuFON6Lv-7oF0sRQLLDA8XjuIZc655NHYIEOQoDPwPQDhkj17gtJVeHbm4xAl98r8Tt

 
[AB#7174](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7174)

**Comment by MIchaelMainer** [comment]
The next time this occurs, can you log the request-id and time that this error occurred so that we can investigate it. Let us know if this is still a problem.

While you are at it, upgrade to 1.21.0.

**Comment by z2alam** [comment]
Please correct me if I am wrong, the requestId is part of the response, right?
In this case, the request itself got stuck in GetAsync call.
I really wanted to look up the requestId to make it easier for you. The only thing I could get at the time was the timestamp...

We have now moved to the latest versions.
Please advise what other information I should provide if I run into this issue again?

Is it possible to prepare a request-Id, and use it in the GetAsync call? So that we'll know the requestId before the call gets stuck at GetAsync.

Thanks,

**Comment by andtu** [comment]
@MIchaelMainer  We are running into this issue quite frequently and have many repro's. Let's discuss this over a call. Thanks!

**Comment by MIchaelMainer** [comment]
@andrueastman Talked with DeVere about this briefly. We need to investigate how our library handles scenarios where no response is returned. We need to gracefully timeout in case of no response.

**Comment by MIchaelMainer** [comment]
ICM 230245801

**Comment by andrueastman** [comment]
This could be potentially fixed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/223
