### ISSUE TITLE
Reference to type 'IAuthenticationProvider' claims it is defined in 'Microsoft.Graph.Core', but it could not be found

### ISSUE THREAD

**Issue by C-lare-M-oore** [microsoftgraph/msgraph-sdk-dotnet-core#928]
### Describe the bug

I am trying to use the graph api client with a client id and secret, to get user information from entra.  I got all the calls working in postman and now i'm trying to get my azure function app to do the same thing.

### Expected behavior

I have been following various samples to try and do a simple query but every time i try to create a graphserviceclient i get the compile error in the title.

Reference to type 'IAuthenticationProvider' claims it is defined in 'Microsoft.Graph.Core', but it could not be found

### How to reproduce

This is my code (secret removed for obvious reasons
```

string[] scopes = {"https://graph.microsoft.com/.default"};
var clientId = "22820207-4185-47ce-874d-d10f6c3b9535";
var tenantId = "378620f7-aa4a-40ac-902a-2ef913d8ed69";
var clientSecret = "*****";

var clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret);

var httpClient = GraphClientFactory.Create( version: "beta");

var authProvider = new AzureIdentityAuthenticationProvider(clientSecretCredential, scopes);

var adapter = new BaseGraphRequestAdapter(authProvider);

var graphClient = new GraphServiceClient(adapter);
```

var graphClient = new GraphServiceClient(adapter); this line causes the issue

### SDK Version

every version i have tried including latest

### Latest version known to work for scenario above?

none

### Known Workarounds

none

### Debug output

no debugt output because it doesnt compile

### Configuration

Windows 11
x64

**Comment by andrueastman** [comment]
Thanks for raising this @C-lare-M-oore 

Any chance you can confirm the version of the library you are using? Is it the latest version available here? https://www.nuget.org/packages/Microsoft.Graph.core#versions-body-tab
